
export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'ja' | 'pt' | 'nl';

export const SUPPORTED_LANGUAGES: { code: LanguageCode; name: string; flag: string }[] = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
    { code: 'ja', name: '日本語', flag: '🇯🇵' },
    { code: 'pt', name: 'Português', flag: '🇧🇷' },
    { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
];

export const detectUserLanguage = (): LanguageCode => {
    try {
        const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        
        if (timeZone.startsWith('Asia/Tokyo')) return 'ja';
        if (timeZone.includes('Paris') || timeZone.includes('Brussels')) return 'fr';
        if (timeZone.includes('Berlin') || timeZone.includes('Vienna') || timeZone.includes('Zurich')) return 'de';
        if (timeZone.includes('Madrid')) return 'es';
        if (timeZone.includes('Sao_Paulo') || timeZone.includes('Lisbon')) return 'pt';
        if (timeZone.includes('Amsterdam') || timeZone.includes('Rotterdam')) return 'nl'; 
        
        if (timeZone.startsWith('America/')) {
             if (timeZone.includes('Mexico') || timeZone.includes('Bogota') || timeZone.includes('Lima') || timeZone.includes('Santiago') || timeZone.includes('Argentina')) return 'es';
        }

        const navLang = navigator.language.split('-')[0];
        if (['en', 'es', 'fr', 'de', 'ja', 'pt', 'nl'].includes(navLang)) {
            return navLang as LanguageCode;
        }
    } catch (e) {
        console.warn("Language detection failed", e);
    }
    
    return 'en';
};

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
    en: {
        "hero.title": "The Future of Law Meets Cyber Intelligence",
        "hero.subtitle.1": "Your Case, Our Code Guide.",
        "hero.subtitle.2": "Where Justice Meets Algorithms.",
        "nav.home": "Home",
        "nav.templates": "Templates",
        "nav.knowledge": "Knowledge Hub",
        "nav.insights": "Insights",
        "nav.labs": "AI Labs",
        "nav.tools": "Tools",
        "nav.engage": "Engage",
        "nav.about": "About Us",
        "section.toolkit": "Next-Gen Legal Intelligence",
        "section.toolkit.title": "Our AI-Powered Legal Toolkit",
        "section.toolkit.desc": "Deploying advanced neural networks to decode legal complexities. Select a module to begin.",
        "tool.predictor": "Precedent Predictor",
        "tool.predictor.desc": "Leverage historical case data to forecast outcomes and optimize litigation strategies.",
        "tool.riskmeter": "AI Cyber Risk Meter",
        "tool.riskmeter.desc": "Quantify legal exposure in real-time by scanning policies and digital assets.",
        "tool.casedna": "Case DNA Analyzer",
        "tool.casedna.desc": "Deconstruct complex cases into visual timelines, entity maps, and liability graphs.",
        "tool.templates": "Legal Templates",
        "tool.templates.desc": "Instantly generate and customize precision-drafted legal documents.",
        "tool.knowledge": "Knowledge Hub",
        "tool.knowledge.desc": "Navigate global cyber laws with instant, AI-curated jurisdictional overviews.",
        "tool.analyzer": "Document Analyzer",
        "tool.analyzer.desc": "Automated risk detection and inconsistency scanning for high-stakes contracts.",
        "tool.summarizer": "Legal News Summarizer",
        "tool.summarizer.desc": "Stay ahead with real-time, sourced summaries of critical rulings and legislation.",
        "tool.copilot": "AI Legal Copilot",
        "tool.copilot.desc": "Formulate strategic action plans tailored to specific legal scenarios.",
        "footer.disclaimer": "Cyber Legal Experts. For informational purposes only. Not legal advice.",
        "chat.greeting": "How can I help you today with matters of cyber law?",
        "chat.typing": "Cylex is typing...",
        "chat.save": "Save Case Note",
        "chat.history": "Case Notes",
        "chat.save_placeholder": "Enter case title...",
        "chat.save_btn": "Save",
        "chat.cancel": "Cancel",
        "chat.load": "Load",
        "chat.delete": "Delete",
        "chat.no_notes": "No saved case notes found.",
        
        // Tickers
        "ticker.threat.1": "Active Phishing Campaign Targeting Financial Institutions Detected.",
        "ticker.threat.2": "New Zero-Day Exploit Found in Widely Used Server Software.",
        "ticker.threat.3": "Ransomware Attack Disrupts Major Healthcare Provider.",
        "ticker.threat.4": "Data Breach Exposes Personal Information of 1M+ Users.",
        "ticker.threat.5": "Warning Issued for State-Sponsored Espionage Malware.",
        "ticker.insight.1": "Supreme Court Rules on Digital Privacy in Cloud Computing.",
        "ticker.insight.2": "New Precedent Set for IP Theft in a Cross-Border Data Case.",
        "ticker.insight.3": "Landmark GDPR Fine Issued for Non-Compliance.",
        "ticker.insight.4": "Analysis: Recent Ruling on AI-generated Content Copyright.",
        "ticker.insight.5": "Legal Tech Trends: Predictive Analytics in Litigation.",

        // Knowledge Hub
        "knowledge.title": "Cyber Law Knowledge Hub",
        "knowledge.subtitle": "Explore high-level overviews of cyber laws from around the world. Select a region to get started.",
        "knowledge.back": "Back to Regions",
        "knowledge.overview": "Cyber Law Overview",
        "knowledge.fetch": "Fetching latest legal information...",
        "knowledge.sources": "Sources Used",
        "knowledge.disclaimer": "Disclaimer: This information is for educational purposes only and is not a substitute for professional legal advice.",
        "region.eu": "European Union",
        "region.us": "United States",
        "region.br": "Brazil",
        "region.in": "India",
        "region.jp": "Japan",
        "region.au": "Australia",
        
        // Engagement Hub
        "engage.title": "Engagement Hub",
        "engage.subtitle": "Interact with our advanced AI tools in new and exciting ways.",
        "engage.voice.title": "Voice Consultation",
        "engage.voice.desc": "Engage in a real-time, hands-free voice conversation with our Cylex AI assistant.",
        "engage.quiz.title": "Are You Cyber Law Smart?",
        "engage.quiz.desc": "Test your knowledge with our AI-generated quiz on the latest in cyber law.",
        "engage.news.title": "AI Legal Newsletter",
        "engage.news.desc": "Generate a personalized legal newsletter with the latest updates for your specific region.",
        "engage.back": "Back to Hub",

        // Voice Consultation
        "voice.title": "AI Voice Consultation",
        "voice.subtitle": "Speak directly with Cylex for a hands-free consultation.",
        "voice.back": "Back to Hub",
        "voice.status.connected": "Connected",
        "voice.status.connecting": "Connecting...",
        "voice.status.error": "Error",
        "voice.status.disconnected": "Disconnected",
        "voice.btn.start": "Start Consultation",
        "voice.btn.end": "End Consultation",
        "voice.listening": "Cylex is listening...",
        "voice.live.disclaimer": "This is a live consultation. Your microphone is active when connected.",

        // Quiz
        "quiz.title": "Are You Cyber Law Smart?",
        "quiz.subtitle": "A gamified quiz to test your cyber law expertise.",
        "quiz.back": "Back to Hub",
        "quiz.loading": "Generating your quiz...",
        "quiz.complete": "Quiz Complete!",
        "quiz.score": "You scored",
        "quiz.play_again": "Play Again",
        "quiz.question_count": "Question",
        "quiz.of": "of",
        "quiz.explanation": "Explanation:",
        "quiz.next": "Next Question",
        "quiz.finish": "Finish Quiz",
        "quiz.start_prompt": "Ready to test your knowledge?",
        "quiz.start_desc": "Get a unique, AI-generated quiz on cyber law.",
        "quiz.start_btn": "Start Quiz",

        // Newsletter
        "news.title": "AI Legal Newsletter Generator",
        "news.subtitle": "Get a personalized legal newsletter for your specified region.",
        "news.back": "Back to Hub",
        "news.placeholder": "e.g., European Union",
        "news.btn": "Generate",
        "news.loading": "Generating your newsletter...",
        "news.result_title": "Your Custom Newsletter",
        "news.sources": "Sources Used:",

        // About Us
        "about.title": "About Cyber Legal Experts",
        "about.desc": "We stand at the critical intersection of law and technology. Our firm was founded on the principle that the rapid evolution of the digital world requires an equally innovative approach to legal practice.",
        "about.timeline": "A Parallel History: Cyber Law & AI",
        "about.t.1986.title": "Computer Fraud and Abuse Act (CFAA)",
        "about.t.1986.desc": "The first major US legislation addressing computer crime, setting a foundational legal framework for hacking.",
        "about.t.1997.title": "Deep Blue defeats Garry Kasparov",
        "about.t.1997.desc": "IBM's chess computer's victory marked a major milestone in AI's ability to tackle complex strategic tasks.",
        "about.t.2000.title": "E-SIGN Act",
        "about.t.2000.desc": "Legitimized electronic signatures in the US, crucial for the growth of digital commerce and contracts.",
        "about.t.2012.title": "AlexNet wins ImageNet",
        "about.t.2012.desc": "A deep learning model that revolutionized computer vision and kickstarted the modern AI boom.",
        "about.t.2016.title": "General Data Protection Regulation (GDPR)",
        "about.t.2016.desc": "The EU enacted the GDPR, establishing a new global standard for data privacy and user rights.",
        "about.t.2017.title": "Transformers Architecture",
        "about.t.2017.desc": "Google researchers publish 'Attention Is All You Need', introducing the transformer architecture that powers modern LLMs.",
        "about.t.2018.title": "CLOUD Act",
        "about.t.2018.desc": "US law allowing federal law enforcement to compel tech companies to provide requested data stored on servers regardless of location.",
        "about.t.2022.title": "Launch of ChatGPT",
        "about.t.2022.desc": "OpenAI's release of ChatGPT brought generative AI into the mainstream, demonstrating its powerful capabilities to the public.",

        // Insights
        "insights.title": "Cyber Law Insights",
        "insights.subtitle": "Your expert source for analysis on digital law, privacy, and AI governance.",
        "insights.generate": "Generate AI Summary",
        "insights.generating": "Summarizing...",
        "insights.listen": "Listen to Summary",
        "insights.ask": "Ask AI about this article",
        "insights.summary_title": "AI Summary:",
        "insights.a1.title": "The GDPR Impact on AI Development",
        "insights.a1.snippet": "Examining the complex interplay between the EU's General Data Protection Regulation and artificial intelligence.",
        "insights.a1.content": "Two years after its full implementation, the GDPR continues to shape the digital landscape. For AI developers, the regulation presents a unique set of hurdles. The principles of data minimization and purpose limitation often conflict with the data-hungry nature of machine learning models. This article explores several key court rulings that have clarified the scope of 'legitimate interest' as a legal basis for processing data for AI training.",
        "insights.a2.title": "Digital Forensics in the Cloud",
        "insights.a2.snippet": "A deep dive into the legal complexities of conducting digital forensic investigations when data is stored across multiple jurisdictions.",
        "insights.a2.content": "Cloud computing has revolutionized data storage, but it has created a nightmare for digital forensic investigators. When a corporation's data is spread across servers in Ireland, Germany, and the United States, which jurisdiction's laws apply? The U.S. CLOUD Act was a significant attempt to address this, but it often clashes with data sovereignty laws in other nations.",
        "insights.a3.title": "Copyright and AI-Generated Art",
        "insights.a3.snippet": "The rise of generative AI models like DALL-E 2 and Midjourney has sparked a fierce debate in copyright law.",
        "insights.a3.content": "Recent decisions from the U.S. Copyright Office have consistently denied copyright protection to works generated solely by AI, stating that human authorship is a prerequisite. However, the line is blurring. What level of human input in prompting and curating AI output is sufficient to qualify as authorship? This article analyzes the 'work for hire' doctrine and its potential application to AI systems.",

        // Templates
        "templates.title": "Legal Templates Library",
        "templates.subtitle": "Access a collection of ready-to-use legal documents for various cyber law scenarios.",
        "templates.copy": "Copy to Clipboard",
        "templates.copied": "Copied!",
        "templates.customize": "Customize with Cylex AI",
        "templates.category.all": "All",
        "templates.cat.ip": "Intellectual Property",
        "templates.cat.privacy": "Data Privacy",
        "templates.cat.contracts": "Contracts & Agreements",
        
        "templates.t1.title": "Cease and Desist Letter",
        "templates.t1.desc": "A formal demand to stop an illegal activity, such as trademark or copyright infringement.",
        "templates.t1.content": "[Your Name]\n[Address]\n[Date]\n\nDear [Name],\n\nThis letter serves as a formal demand that you immediately CEASE AND DESIST all unauthorized use of [Your Company]'s intellectual property. It has come to our attention that you are using our material without consent. We demand you remove it immediately. Failure to comply will result in legal action.\n\nSincerely,\n[Your Name]",

        "templates.t2.title": "Privacy Policy",
        "templates.t2.desc": "A basic template for a website privacy policy outlining data collection and use.",
        "templates.t2.content": "PRIVACY POLICY\n\n[Your Company] collects data to improve our service. We may collect Personal Data (Name, Email) and Usage Data. We use this to maintain the Service and notify you of changes. We respect your data rights.",

        "templates.t3.title": "Non-Disclosure Agreement (NDA)",
        "templates.t3.desc": "A standard mutual NDA to protect confidential information between two parties.",
        "templates.t3.content": "MUTUAL NON-DISCLOSURE AGREEMENT\n\nThis Agreement is between [Party 1] and [Party 2]. 'Confidential Information' means any data proprietary to the disclosing party. Both parties agree not to disclose this information to third parties. This agreement survives for [Years] years.",

        "templates.t4.title": "Data Breach Notification",
        "templates.t4.desc": "A template for notifying affected individuals about a data breach.",
        "templates.t4.content": "NOTICE OF DATA INCIDENT\n\nDear [Name],\n\nWe are writing to inform you of a data security incident. On [Date], we discovered unauthorized access to our systems. Your personal information may have been involved. We are taking steps to secure our systems. Please remain vigilant.",

        "templates.t5.title": "Terms of Service",
        "templates.t5.desc": "Standard terms and conditions for governing the use of a website or application.",
        "templates.t5.content": "TERMS OF SERVICE\n\nWelcome to [Website Name]. By accessing our site, you agree to these Terms.\n\n1. Use of Site: You may not use the site for illegal purposes.\n2. Intellectual Property: All content is owned by [Company].\n3. Termination: We reserve the right to terminate access for violations.\n4. Governing Law: These terms are governed by the laws of [Jurisdiction].",

        "templates.t6.title": "Cookie Policy",
        "templates.t6.desc": "A policy explaining the use of cookies to ensure compliance with privacy laws like GDPR.",
        "templates.t6.content": "COOKIE POLICY\n\n[Your Company] uses cookies to enhance user experience.\n\n1. Types of Cookies: We use Essential, Analytics, and Marketing cookies.\n2. Consent: By using our site, you consent to our use of cookies.\n3. Management: You can disable cookies in your browser settings, though this may affect site functionality.",

        "templates.t7.title": "Website Disclaimer",
        "templates.t7.desc": "Limits liability regarding the information provided on your website.",
        "templates.t7.content": "WEBSITE DISCLAIMER\n\nThe information provided by [Your Company] on [Website Name] is for general informational purposes only. All information is provided in good faith, however we make no representation or warranty of any kind regarding accuracy, adequacy, validity, reliability, availability or completeness of any information on the Site.",

        "templates.t8.title": "Software License Agreement",
        "templates.t8.desc": "An agreement for licensing software to end-users (EULA).",
        "templates.t8.content": "END USER LICENSE AGREEMENT (EULA)\n\nThis Agreement is between [Licensor] and [Licensee].\n\n1. Grant of License: Licensor grants Licensee a non-exclusive, non-transferable license to use the Software.\n2. Restrictions: Licensee shall not reverse engineer, decompile, or disassemble the Software.\n3. Termination: This license is effective until terminated.",

        // Labs
        "labs.title": "AI Labs",
        "labs.subtitle": "A glimpse into the future. Here we showcase our experimental projects at the bleeding edge of AI and law.",
        "labs.coming_soon": "Coming Soon",
        "labs.exp1.title": "Phishing Evidence Classifier",
        "labs.exp1.desc": "An experimental model that analyzes email headers, body content, and attachments to classify potential phishing attempts and automatically extract key evidence for legal action.",
        "labs.exp2.title": "Smart Contract Risk Scanner",
        "labs.exp2.desc": "Utilizes static and dynamic analysis to scan blockchain smart contracts for common vulnerabilities (e.g., reentrancy attacks) and potential legal ambiguities before deployment.",
        "labs.exp3.title": "Predictive E-Discovery Tagger",
        "labs.exp3.desc": "A proof-of-concept tool that uses natural language processing to predict the relevance of documents in large e-discovery datasets, aiming to significantly reduce manual review time.",
        "labs.exp4.title": "Deepfake Detection API",
        "labs.exp4.desc": "A research project focused on creating a service that can analyze video evidence to provide a probability score for deepfake manipulation, crucial for authenticating digital media.",
        "labs.status.experimental": "Experimental",
        "labs.status.development": "In Development",
        "labs.status.concept": "Concept",

        // Document Analyzer
        "analyzer.title": "AI Document Analyzer",
        "analyzer.subtitle": "Upload a legal document (.txt, .md) for risk and inconsistency analysis.",
        "analyzer.select": "Select a file",
        "analyzer.change": "Change file",
        "analyzer.btn": "Analyze Document",
        "analyzer.loading": "Analyzing Document",
        "analyzer.loading.desc": "Detecting risks and inconsistencies...",
        "analyzer.results": "Analysis Results:",

        // News Summarizer
        "summarizer.title": "Legal News Summarizer",
        "summarizer.subtitle": "Get AI-powered summaries of the latest legal news and rulings, with sources.",
        "summarizer.placeholder": "e.g., recent data privacy laws",
        "summarizer.btn": "Summarize",
        "summarizer.results": "Summary:",
        "summarizer.sources": "Sources:",

        // Legal Copilot
        "copilot.title": "AI Legal Copilot",
        "copilot.subtitle": "Describe your situation to receive a personalized, step-by-step action plan.",
        "copilot.label": "Case Details",
        "copilot.placeholder": "Describe the incident, parties involved, and your desired outcome. For example: 'I am a small business owner and I suspect a former employee stole our client list...'",
        "copilot.btn": "Generate Action Plan",
        "copilot.results": "Generated Action Plan:",
        "copilot.disclaimer": "Disclaimer: This is an AI-generated plan for informational purposes only and does not constitute legal advice.",

        // Case DNA
        "casedna.title": "AI Case DNA Analyzer",
        "casedna.subtitle": "Visually map your case by extracting timelines, entities, evidence, and liabilities.",
        "casedna.placeholder": "Describe the incident, upload a document, or paste text here...",
        "casedna.upload": "Upload Document (.txt, .md)",
        "casedna.or": "OR",
        "casedna.btn": "Analyze Case DNA",
        "casedna.map": "Case DNA Map",
        "casedna.timeline": "Timeline",
        "casedna.entities": "Key Entities",
        "casedna.evidence": "Evidence Patterns",
        "casedna.liabilities": "Potential Legal Liabilities",
        "casedna.modal.timeline": "Timeline Event Details",
        "casedna.modal.entity": "Entity Details",

        // Risk Meter
        "riskmeter.title": "AI Cyber Risk Meter",
        "riskmeter.subtitle": "Paste your privacy policy, terms of service, or contract text below for a risk assessment.",
        "riskmeter.placeholder": "Paste text here...",
        "riskmeter.btn": "Assess Risk",
        "riskmeter.results": "Risk Assessment Results",
        "riskmeter.level": "Overall Risk Level:",
        "riskmeter.risk": "Identified Risk",
        "riskmeter.rec": "Recommendation",

        // Precedent Predictor
        "predictor.title": "AI Precedent Predictor",
        "predictor.subtitle": "Analyze your case against historical data to predict likely outcomes and strategies.",
        "predictor.placeholder": "Describe your case here. Include key facts, parties involved, and the legal questions at hand...",
        "predictor.btn": "Predict Outcome",
        "predictor.dashboard": "Prediction Dashboard",
        "predictor.outcomes": "Predicted Outcomes",
        "predictor.sections": "Key Legal Sections",
        "predictor.strategies": "Suggested Strategies",
        "predictor.confidence": "Confidence",
        "predictor.likelihood": "Likelihood",
    },
    es: {
        // ... (existing translations) ...
        "hero.title": "El Futuro de la Ley Encuentra la Inteligencia Cibernética",
        "hero.subtitle.1": "Su Caso, Nuestro Código.",
        "hero.subtitle.2": "Donde la Justicia Encuentra los Algoritmos.",
        "nav.home": "Inicio",
        "nav.templates": "Plantillas",
        "nav.knowledge": "Conocimiento",
        "nav.insights": "Perspectivas",
        "nav.labs": "Laboratorios",
        "nav.tools": "Herramientas",
        "nav.engage": "Interactuar",
        "nav.about": "Nosotros",
        "section.toolkit": "Inteligencia Legal de Próxima Generación",
        "section.toolkit.title": "Nuestro Kit Legal Impulsado por IA",
        "section.toolkit.desc": "Implementando redes neuronales avanzadas para decodificar complejidades legales.",
        "region.eu": "Unión Europea",
        "region.us": "Estados Unidos",
        "region.br": "Brasil",
        "region.in": "India",
        "region.jp": "Japón",
        "region.au": "Australia",
        "engage.title": "Centro de Participación",
        "engage.subtitle": "Interactúa con nuestras herramientas avanzadas de IA.",
        "engage.voice.title": "Consulta por Voz",
        "engage.voice.desc": "Hable directamente con Cylex para una consulta manos libres.",
        "engage.quiz.title": "¿Eres Experto en Ciberleyes?",
        "engage.quiz.desc": "Pon a prueba tus conocimientos con nuestro cuestionario generado por IA.",
        "engage.news.title": "Boletín Legal IA",
        "engage.news.desc": "Genere un boletín personalizado con las últimas actualizaciones legales.",
        "engage.back": "Volver",
        "voice.title": "Consulta de Voz IA",
        "voice.subtitle": "Hable directamente con Cylex para una consulta manos libres.",
        "voice.back": "Volver",
        "voice.status.connected": "Conectado",
        "voice.status.connecting": "Conectando...",
        "voice.status.error": "Error",
        "voice.status.disconnected": "Desconectado",
        "voice.btn.start": "Iniciar Consulta",
        "voice.btn.end": "Terminar Consulta",
        "voice.listening": "Cylex está escuchando...",
        "voice.live.disclaimer": "Esta es una consulta en vivo. Su micrófono está activo.",
        "quiz.title": "¿Eres Experto en Ciberleyes?",
        "quiz.subtitle": "Un cuestionario gamificado para probar tu experiencia.",
        "quiz.back": "Volver",
        "quiz.loading": "Generando su cuestionario...",
        "quiz.complete": "¡Cuestionario Completo!",
        "quiz.score": "Su puntuación",
        "quiz.play_again": "Jugar de Nuevo",
        "quiz.question_count": "Pregunta",
        "quiz.of": "de",
        "quiz.explanation": "Explicación:",
        "quiz.next": "Siguiente Pregunta",
        "quiz.finish": "Terminar",
        "quiz.start_prompt": "¿Listo para probar tu conocimiento?",
        "quiz.start_desc": "Obtén un cuestionario único generado por IA.",
        "quiz.start_btn": "Iniciar Cuestionario",
        "news.title": "Generador de Boletines Legales",
        "news.subtitle": "Obtenga un boletín legal personalizado para su región.",
        "news.back": "Volver",
        "news.placeholder": "ej., Unión Europea",
        "news.btn": "Generar",
        "news.loading": "Generando su boletín...",
        "news.result_title": "Su Boletín Personalizado",
        "news.sources": "Fuentes Utilizadas:",
        "templates.title": "Biblioteca de Plantillas",
        "templates.subtitle": "Acceda a documentos legales listos para usar.",
        "templates.copy": "Copiar",
        "templates.copied": "¡Copiado!",
        "templates.customize": "Personalizar",
        "templates.category.all": "Todo",
        "templates.cat.ip": "Propiedad Intelectual",
        "templates.cat.privacy": "Privacidad de Datos",
        "templates.cat.contracts": "Contratos",
        "templates.t1.title": "Carta de Cese y Desistimiento",
        "templates.t1.desc": "Demanda formal para detener una actividad ilegal.",
        "templates.t1.content": "[Su Nombre]\n[Dirección]\n[Fecha]\n\nEstimado [Nombre],\n\nEsta carta sirve como demanda formal para que CESE Y DESISTA inmediatamente todo uso no autorizado de la propiedad intelectual de [Su Empresa]. Exigimos que lo elimine de inmediato. El incumplimiento resultará en acciones legales.\n\nAtentamente,\n[Su Nombre]",
        "templates.t2.title": "Política de Privacidad",
        "templates.t2.desc": "Plantilla básica para la política de privacidad de un sitio web.",
        "templates.t2.content": "POLÍTICA DE PRIVACIDAD\n\n[Su Empresa] recopila datos para mejorar nuestro servicio. Podemos recopilar Datos Personales (Nombre, Email) y Datos de Uso. Respetamos sus derechos de datos.",
        "templates.t3.title": "Acuerdo de Confidencialidad (NDA)",
        "templates.t3.desc": "NDA mutuo estándar para proteger información confidencial.",
        "templates.t3.content": "ACUERDO DE CONFIDENCIALIDAD MUTUO\n\nEste Acuerdo es entre [Parte 1] y [Parte 2]. 'Información Confidencial' significa cualquier dato propietario de la parte reveladora. Ambas partes acuerdan no revelar esta información. Este acuerdo sobrevive por [Años] años.",
        "templates.t4.title": "Notificación de Violación de Datos",
        "templates.t4.desc": "Plantilla para notificar sobre una violación de datos.",
        "templates.t4.content": "AVISO DE INCIDENTE DE DATOS\n\nEstimado [Nombre],\n\nLe escribimos para informarle de un incidente de seguridad. El [Fecha], descubrimos un acceso no autorizado. Su información personal puede haber estado involucrada. Estamos tomando medidas.",
        
        "templates.t5.title": "Términos de Servicio",
        "templates.t5.desc": "Términos y condiciones estándar para regir el uso de un sitio web o aplicación.",
        "templates.t5.content": "TÉRMINOS DE SERVICIO\n\nBienvenido a [Nombre del Sitio]. Al acceder a nuestro sitio, acepta estos Términos.\n\n1. Uso del Sitio: No puede usar el sitio para fines ilegales.\n2. Propiedad Intelectual: Todo el contenido es propiedad de [Empresa].\n3. Terminación: Nos reservamos el derecho de terminar el acceso por violaciones.\n4. Ley Aplicable: Estos términos se rigen por las leyes de [Jurisdicción].",
        "templates.t6.title": "Política de Cookies",
        "templates.t6.desc": "Política que explica el uso de cookies para el cumplimiento de leyes como el RGPD.",
        "templates.t6.content": "POLÍTICA DE COOKIES\n\n[Su Empresa] utiliza cookies para mejorar la experiencia del usuario.\n\n1. Tipos de Cookies: Utilizamos cookies Esenciales, Analíticas y de Marketing.\n2. Consentimiento: Al usar nuestro sitio, acepta nuestro uso de cookies.\n3. Gestión: Puede desactivar las cookies en la configuración de su navegador.",
        "templates.t7.title": "Descargo de Responsabilidad",
        "templates.t7.desc": "Limita la responsabilidad con respecto a la información proporcionada en su sitio web.",
        "templates.t7.content": "DESCARGO DE RESPONSABILIDAD\n\nLa información proporcionada por [Su Empresa] en [Nombre del Sitio] es solo para fines informativos generales. Toda la información se proporciona de buena fe, sin embargo, no hacemos representación ni garantía de ningún tipo con respecto a la precisión o integridad.",
        "templates.t8.title": "Acuerdo de Licencia de Software",
        "templates.t8.desc": "Acuerdo para licenciar software a usuarios finales (EULA).",
        "templates.t8.content": "ACUERDO DE LICENCIA DE USUARIO FINAL (EULA)\n\nEste Acuerdo es entre [Licenciante] y [Licenciatario].\n\n1. Concesión de Licencia: El Licenciante otorga al Licenciatario una licencia no exclusiva para usar el Software.\n2. Restricciones: El Licenciatario no podrá realizar ingeniería inversa del Software.\n3. Terminación: Esta licencia es efectiva hasta su terminación.",

        "insights.a1.title": "Impacto del RGPD en la IA",
        "insights.a1.snippet": "Examinando la interacción entre el RGPD de la UE y la inteligencia artificial.",
        "insights.a1.content": "Dos años después de su implementación, el RGPD sigue dando forma al panorama digital. Para los desarrolladores de IA, presenta desafíos únicos. Los principios de minimización de datos a menudo entran en conflicto con el aprendizaje automático.",
        "insights.a2.title": "Forense Digital en la Nube",
        "insights.a2.snippet": "Complejidades legales de investigaciones forenses en la nube.",
        "insights.a2.content": "La computación en la nube ha revolucionado el almacenamiento, pero ha creado una pesadilla para los investigadores forenses. Cuando los datos están en varios países, ¿qué ley aplica?",
        "insights.a3.title": "Derechos de Autor y Arte IA",
        "insights.a3.snippet": "El auge de la IA generativa ha desatado un debate sobre derechos de autor.",
        "insights.a3.content": "Decisiones recientes han negado la protección de derechos de autor a obras generadas únicamente por IA. Sin embargo, la línea se está desdibujando.",
        "labs.title": "Laboratorios de IA",
        "labs.subtitle": "Un vistazo al futuro. Proyectos experimentales en la vanguardia de la IA y la ley.",
        "labs.coming_soon": "Próximamente",
        "labs.status.experimental": "Experimental",
        "labs.status.development": "En Desarrollo",
        "labs.status.concept": "Concepto",
        "tool.predictor": "Predictor de Precedentes",
        "tool.predictor.desc": "Pronostique resultados y optimice estrategias de litigio.",
        "tool.riskmeter": "Medidor de Riesgo Cibernético",
        "tool.riskmeter.desc": "Cuantifique la exposición legal en tiempo real.",
        "tool.casedna": "Analizador de ADN del Caso",
        "tool.casedna.desc": "Deconstruya casos complejos en líneas de tiempo visuales.",
        "tool.templates": "Plantillas Legales",
        "tool.templates.desc": "Genere y personalice documentos legales.",
        "tool.knowledge": "Centro de Conocimiento",
        "tool.knowledge.desc": "Navegue por las leyes cibernéticas globales.",
        "tool.analyzer": "Analizador de Documentos",
        "tool.analyzer.desc": "Detección automatizada de riesgos.",
        "tool.summarizer": "Resumidor de Noticias",
        "tool.summarizer.desc": "Manténgase al día con resúmenes en tiempo real.",
        "tool.copilot": "Copiloto Legal IA",
        "tool.copilot.desc": "Formule planes de acción estratégicos.",
        "chat.typing": "Cylex está escribiendo...",
        "analyzer.title": "Analizador de Documentos IA",
        "analyzer.subtitle": "Suba un documento legal para análisis de riesgos.",
        "analyzer.select": "Seleccionar archivo",
        "analyzer.change": "Cambiar archivo",
        "analyzer.btn": "Analizar Documento",
        "analyzer.loading": "Analizando Documento",
        "analyzer.loading.desc": "Detectando riesgos e inconsistencias...",
        "analyzer.results": "Resultados del Análisis:",
        "summarizer.title": "Resumidor de Noticias Legales",
        "summarizer.subtitle": "Obtenga resúmenes impulsados por IA de las últimas noticias legales.",
        "summarizer.placeholder": "ej., leyes de privacidad de datos recientes",
        "summarizer.btn": "Resumir",
        "summarizer.results": "Resumen:",
        "summarizer.sources": "Fuentes:",
        "copilot.title": "Copiloto Legal IA",
        "copilot.subtitle": "Describa su situación para recibir un plan de acción.",
        "copilot.label": "Detalles del Caso",
        "copilot.placeholder": "Describa el incidente, las partes involucradas y su resultado deseado...",
        "copilot.btn": "Generar Plan",
        "copilot.results": "Plan de Acción Generado:",
        "copilot.disclaimer": "Descargo de responsabilidad: Esto no constituye asesoramiento legal.",
        "casedna.title": "Analizador de ADN del Caso",
        "casedna.subtitle": "Mapee visualmente su caso extrayendo líneas de tiempo y entidades.",
        "casedna.placeholder": "Describa el incidente o suba un documento...",
        "casedna.upload": "Subir Documento",
        "casedna.or": "O",
        "casedna.btn": "Analizar ADN",
        "casedna.map": "Mapa de ADN del Caso",
        "casedna.timeline": "Línea de Tiempo",
        "casedna.entities": "Entidades Clave",
        "casedna.evidence": "Patrones de Evidencia",
        "casedna.liabilities": "Posibles Responsabilidades",
        "riskmeter.title": "Medidor de Riesgo Cibernético",
        "riskmeter.subtitle": "Pegue su política de privacidad o contrato para evaluar riesgos.",
        "riskmeter.placeholder": "Pegue el texto aquí...",
        "riskmeter.btn": "Evaluar Riesgo",
        "riskmeter.results": "Resultados de la Evaluación",
        "riskmeter.level": "Nivel de Riesgo General:",
        "riskmeter.risk": "Riesgo Identificado",
        "riskmeter.rec": "Recomendación",
        "predictor.title": "Predictor de Precedentes",
        "predictor.subtitle": "Analice su caso contra datos históricos.",
        "predictor.placeholder": "Describa su caso aquí...",
        "predictor.btn": "Predecir Resultado",
        "predictor.dashboard": "Panel de Predicción",
        "predictor.outcomes": "Resultados Predichos",
        "predictor.sections": "Secciones Legales Clave",
        "predictor.strategies": "Estrategias Sugeridas",
        "about.title": "Sobre Expertos Legales Cibernéticos",
        "about.desc": "Estamos en la intersección crítica de la ley y la tecnología. Nuestra firma se fundó sobre el principio de que la rápida evolución del mundo digital requiere un enfoque igualmente innovador de la práctica legal.",
        "about.timeline": "Una Historia Paralela: Ciberleyes e IA",
        "about.t.1986.title": "Ley de Fraude y Abuso Informático (CFAA)",
        "about.t.1986.desc": "La primera gran legislación estadounidense sobre delitos informáticos.",
        "about.t.1997.title": "Deep Blue derrota a Garry Kasparov",
        "about.t.1997.desc": "La victoria de la computadora de ajedrez de IBM marcó un hito en la IA.",
        "about.t.2000.title": "Ley E-SIGN",
        "about.t.2000.desc": "Legitimó las firmas electrónicas en EE. UU.",
        "about.t.2012.title": "AlexNet gana ImageNet",
        "about.t.2012.desc": "Modelo de aprendizaje profundo que revolucionó la visión por computadora.",
        "about.t.2016.title": "Reglamento General de Protección de Datos (RGPD)",
        "about.t.2016.desc": "La UE promulgó el RGPD, estableciendo un nuevo estándar global.",
        "about.t.2017.title": "Arquitectura Transformers",
        "about.t.2017.desc": "Investigadores de Google publican 'Attention Is All You Need'.",
        "about.t.2018.title": "Ley CLOUD",
        "about.t.2018.desc": "Ley de EE. UU. que permite a las fuerzas del orden obligar a las empresas a proporcionar datos.",
        "about.t.2022.title": "Lanzamiento de ChatGPT",
        "about.t.2022.desc": "El lanzamiento de ChatGPT por OpenAI llevó la IA generativa a la corriente principal.",
        "knowledge.title": "Centro de Conocimiento Legal",
        "knowledge.subtitle": "Explore descripciones generales de leyes cibernéticas.",
        "knowledge.back": "Volver a Regiones",
        "knowledge.overview": "Resumen Legal",
        "knowledge.fetch": "Buscando información legal...",
        "knowledge.sources": "Fuentes Utilizadas",
        "knowledge.disclaimer": "Descargo de responsabilidad: Solo para fines educativos.",
        "insights.title": "Perspectivas de Ciberleyes",
        "insights.subtitle": "Su fuente experta de análisis.",
        "insights.generate": "Generar Resumen IA",
        "insights.generating": "Resumiendo...",
        "insights.listen": "Escuchar Resumen",
        "insights.ask": "Preguntar a IA",
        "insights.summary_title": "Resumen IA:",
        "ticker.threat.1": "Detectada campaña activa de phishing dirigida a instituciones financieras.",
        "ticker.threat.2": "Nuevo exploit de día cero encontrado en software de servidor ampliamente utilizado.",
        "ticker.threat.3": "Ataque de ransomware interrumpe importante proveedor de atención médica.",
        "ticker.threat.4": "Violación de datos expone información personal de más de 1M de usuarios.",
        "ticker.threat.5": "Advertencia emitida por malware de espionaje patrocinado por el estado.",
        "ticker.insight.1": "La Corte Suprema dictamina sobre privacidad digital en computación en la nube.",
        "ticker.insight.2": "Nuevo precedente establecido para robo de PI en un caso de datos transfronterizos.",
        "ticker.insight.3": "Multa histórica del RGPD emitida por incumplimiento.",
        "ticker.insight.4": "Análisis: Fallo reciente sobre derechos de autor de contenido generado por IA.",
        "ticker.insight.5": "Tendencias de tecnología legal: Análisis predictivo en litigios.",
        "chat.save": "Guardar Nota del Caso",
        "chat.history": "Notas del Caso",
        "chat.save_placeholder": "Ingrese título del caso...",
        "chat.save_btn": "Guardar",
        "chat.cancel": "Cancelar",
        "chat.load": "Cargar",
        "chat.delete": "Borrar",
        "chat.no_notes": "No se encontraron notas guardadas.",
    },
    // ... Other languages (assuming structure is maintained or abbreviated for brevity if allowed, but full XML requires full content. Since I only need to add new keys, I will add them to all langs for consistency)
    fr: {
        // ...
        "chat.save": "Enregistrer la Note",
        "chat.history": "Notes de Cas",
        "chat.save_placeholder": "Entrez le titre...",
        "chat.save_btn": "Enregistrer",
        "chat.cancel": "Annuler",
        "chat.load": "Charger",
        "chat.delete": "Supprimer",
        "chat.no_notes": "Aucune note trouvée.",
         // ... (existing translations)
    },
    de: {
        // ...
        "chat.save": "Fallnotiz Speichern",
        "chat.history": "Fallnotizen",
        "chat.save_placeholder": "Falltitel eingeben...",
        "chat.save_btn": "Speichern",
        "chat.cancel": "Abbrechen",
        "chat.load": "Laden",
        "chat.delete": "Löschen",
        "chat.no_notes": "Keine gespeicherten Notizen gefunden.",
        // ... (existing translations)
    },
    ja: {
        // ...
        "chat.save": "ケースノートを保存",
        "chat.history": "ケースノート",
        "chat.save_placeholder": "ケースタイトルを入力...",
        "chat.save_btn": "保存",
        "chat.cancel": "キャンセル",
        "chat.load": "ロード",
        "chat.delete": "削除",
        "chat.no_notes": "保存されたノートはありません。",
        // ... (existing translations)
    },
    pt: {
        // ...
        "chat.save": "Salvar Nota do Caso",
        "chat.history": "Notas do Caso",
        "chat.save_placeholder": "Digite o título do caso...",
        "chat.save_btn": "Salvar",
        "chat.cancel": "Cancelar",
        "chat.load": "Carregar",
        "chat.delete": "Excluir",
        "chat.no_notes": "Nenhuma nota encontrada.",
        // ... (existing translations)
    },
    nl: {
        // ...
        "chat.save": "Zaaknotitie Opslaan",
        "chat.history": "Zaaknotities",
        "chat.save_placeholder": "Voer zaaktitel in...",
        "chat.save_btn": "Opslaan",
        "chat.cancel": "Annuleren",
        "chat.load": "Laden",
        "chat.delete": "Verwijderen",
        "chat.no_notes": "Geen opgeslagen notities gevonden.",
        // ... (existing translations)
    }
};

export const translate = (key: string, lang: LanguageCode): string => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en'][key] || key;
};
