
export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'ja' | 'pt' | 'nl';

export const SUPPORTED_LANGUAGES: { code: LanguageCode; name: string; flag: string }[] = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
    { code: 'ja', name: '日本語', flag: '🇯🇵' },
    { code: 'pt', name: 'Português', flag: '🇧🇷' },
    { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
];

export const detectUserLanguage = (): LanguageCode => {
    try {
        const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        
        if (timeZone.startsWith('Asia/Tokyo')) return 'ja';
        if (timeZone.includes('Paris') || timeZone.includes('Brussels')) return 'fr';
        if (timeZone.includes('Berlin') || timeZone.includes('Vienna') || timeZone.includes('Zurich')) return 'de';
        if (timeZone.includes('Madrid')) return 'es';
        if (timeZone.includes('Sao_Paulo') || timeZone.includes('Lisbon')) return 'pt';
        if (timeZone.includes('Amsterdam') || timeZone.includes('Rotterdam')) return 'nl'; 
        
        if (timeZone.startsWith('America/')) {
             if (timeZone.includes('Mexico') || timeZone.includes('Bogota') || timeZone.includes('Lima') || timeZone.includes('Santiago') || timeZone.includes('Argentina')) return 'es';
        }

        const navLang = navigator.language.split('-')[0];
        if (['en', 'es', 'fr', 'de', 'ja', 'pt', 'nl'].includes(navLang)) {
            return navLang as LanguageCode;
        }
    } catch (e) {
        console.warn("Language detection failed", e);
    }
    
    return 'en';
};

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
    en: {
        "hero.title": "The Future of Law Meets Cyber Intelligence",
        "hero.subtitle.1": "Your Case, Our Code Guide.",
        "hero.subtitle.2": "Where Justice Meets Algorithms.",
        "nav.home": "Home",
        "nav.templates": "Templates",
        "nav.knowledge": "Knowledge Hub",
        "nav.insights": "Insights",
        "nav.labs": "AI Labs",
        "nav.tools": "Tools",
        "nav.engage": "Engage",
        "nav.about": "About Us",
        "section.toolkit": "Next-Gen Legal Intelligence",
        "section.toolkit.title": "Our AI-Powered Legal Toolkit",
        "section.toolkit.desc": "Deploying advanced neural networks to decode legal complexities. Select a module to begin.",
        "tool.predictor": "Precedent Predictor",
        "tool.predictor.desc": "Leverage historical case data to forecast outcomes and optimize litigation strategies.",
        "tool.riskmeter": "AI Cyber Risk Meter",
        "tool.riskmeter.desc": "Quantify legal exposure in real-time by scanning policies and digital assets.",
        "tool.casedna": "Case DNA Analyzer",
        "tool.casedna.desc": "Deconstruct complex cases into visual timelines, entity maps, and liability graphs.",
        "tool.templates": "Legal Templates",
        "tool.templates.desc": "Instantly generate and customize precision-drafted legal documents.",
        "tool.knowledge": "Knowledge Hub",
        "tool.knowledge.desc": "Navigate global cyber laws with instant, AI-curated jurisdictional overviews.",
        "tool.analyzer": "Document Analyzer",
        "tool.analyzer.desc": "Automated risk detection and inconsistency scanning for high-stakes contracts.",
        "tool.summarizer": "Legal News Summarizer",
        "tool.summarizer.desc": "Stay ahead with real-time, sourced summaries of critical rulings and legislation.",
        "tool.copilot": "AI Legal Copilot",
        "tool.copilot.desc": "Formulate strategic action plans tailored to specific legal scenarios.",
        "footer.disclaimer": "Cyber Legal Experts. For informational purposes only. Not legal advice.",
        "chat.greeting": "How can I help you today with matters of cyber law?",
        "chat.typing": "Cylex is typing...",
        
        // Tickers
        "ticker.threat.1": "Active Phishing Campaign Targeting Financial Institutions Detected.",
        "ticker.threat.2": "New Zero-Day Exploit Found in Widely Used Server Software.",
        "ticker.threat.3": "Ransomware Attack Disrupts Major Healthcare Provider.",
        "ticker.threat.4": "Data Breach Exposes Personal Information of 1M+ Users.",
        "ticker.threat.5": "Warning Issued for State-Sponsored Espionage Malware.",
        "ticker.insight.1": "Supreme Court Rules on Digital Privacy in Cloud Computing.",
        "ticker.insight.2": "New Precedent Set for IP Theft in a Cross-Border Data Case.",
        "ticker.insight.3": "Landmark GDPR Fine Issued for Non-Compliance.",
        "ticker.insight.4": "Analysis: Recent Ruling on AI-generated Content Copyright.",
        "ticker.insight.5": "Legal Tech Trends: Predictive Analytics in Litigation.",

        // Knowledge Hub
        "knowledge.title": "Cyber Law Knowledge Hub",
        "knowledge.subtitle": "Explore high-level overviews of cyber laws from around the world. Select a region to get started.",
        "knowledge.back": "Back to Regions",
        "knowledge.overview": "Cyber Law Overview",
        "knowledge.fetch": "Fetching latest legal information...",
        "knowledge.sources": "Sources Used",
        "knowledge.disclaimer": "Disclaimer: This information is for educational purposes only and is not a substitute for professional legal advice.",
        "region.eu": "European Union",
        "region.us": "United States",
        "region.br": "Brazil",
        "region.in": "India",
        "region.jp": "Japan",
        "region.au": "Australia",
        
        // Engagement Hub
        "engage.title": "Engagement Hub",
        "engage.subtitle": "Interact with our advanced AI tools in new and exciting ways.",
        "engage.voice.title": "Voice Consultation",
        "engage.voice.desc": "Engage in a real-time, hands-free voice conversation with our Cylex AI assistant.",
        "engage.quiz.title": "Are You Cyber Law Smart?",
        "engage.quiz.desc": "Test your knowledge with our AI-generated quiz on the latest in cyber law.",
        "engage.news.title": "AI Legal Newsletter",
        "engage.news.desc": "Generate a personalized legal newsletter with the latest updates for your specific region.",
        "engage.back": "Back to Hub",

        // Voice Consultation
        "voice.title": "AI Voice Consultation",
        "voice.subtitle": "Speak directly with Cylex for a hands-free consultation.",
        "voice.back": "Back to Hub",
        "voice.status.connected": "Connected",
        "voice.status.connecting": "Connecting...",
        "voice.status.error": "Error",
        "voice.status.disconnected": "Disconnected",
        "voice.btn.start": "Start Consultation",
        "voice.btn.end": "End Consultation",
        "voice.listening": "Cylex is listening...",
        "voice.live.disclaimer": "This is a live consultation. Your microphone is active when connected.",

        // Quiz
        "quiz.title": "Are You Cyber Law Smart?",
        "quiz.subtitle": "A gamified quiz to test your cyber law expertise.",
        "quiz.back": "Back to Hub",
        "quiz.loading": "Generating your quiz...",
        "quiz.complete": "Quiz Complete!",
        "quiz.score": "You scored",
        "quiz.play_again": "Play Again",
        "quiz.question_count": "Question",
        "quiz.of": "of",
        "quiz.explanation": "Explanation:",
        "quiz.next": "Next Question",
        "quiz.finish": "Finish Quiz",
        "quiz.start_prompt": "Ready to test your knowledge?",
        "quiz.start_desc": "Get a unique, AI-generated quiz on cyber law.",
        "quiz.start_btn": "Start Quiz",

        // Newsletter
        "news.title": "AI Legal Newsletter Generator",
        "news.subtitle": "Get a personalized legal newsletter for your specified region.",
        "news.back": "Back to Hub",
        "news.placeholder": "e.g., European Union",
        "news.btn": "Generate",
        "news.loading": "Generating your newsletter...",
        "news.result_title": "Your Custom Newsletter",
        "news.sources": "Sources Used:",

        // About Us
        "about.title": "About Cyber Legal Experts",
        "about.desc": "We stand at the critical intersection of law and technology. Our firm was founded on the principle that the rapid evolution of the digital world requires an equally innovative approach to legal practice.",
        "about.timeline": "A Parallel History: Cyber Law & AI",
        "about.t.1986.title": "Computer Fraud and Abuse Act (CFAA)",
        "about.t.1986.desc": "The first major US legislation addressing computer crime, setting a foundational legal framework for hacking.",
        "about.t.1997.title": "Deep Blue defeats Garry Kasparov",
        "about.t.1997.desc": "IBM's chess computer's victory marked a major milestone in AI's ability to tackle complex strategic tasks.",
        "about.t.2000.title": "E-SIGN Act",
        "about.t.2000.desc": "Legitimized electronic signatures in the US, crucial for the growth of digital commerce and contracts.",
        "about.t.2012.title": "AlexNet wins ImageNet",
        "about.t.2012.desc": "A deep learning model that revolutionized computer vision and kickstarted the modern AI boom.",
        "about.t.2016.title": "General Data Protection Regulation (GDPR)",
        "about.t.2016.desc": "The EU enacted the GDPR, establishing a new global standard for data privacy and user rights.",
        "about.t.2017.title": "Transformers Architecture",
        "about.t.2017.desc": "Google researchers publish 'Attention Is All You Need', introducing the transformer architecture that powers modern LLMs.",
        "about.t.2018.title": "CLOUD Act",
        "about.t.2018.desc": "US law allowing federal law enforcement to compel tech companies to provide requested data stored on servers regardless of location.",
        "about.t.2022.title": "Launch of ChatGPT",
        "about.t.2022.desc": "OpenAI's release of ChatGPT brought generative AI into the mainstream, demonstrating its powerful capabilities to the public.",

        // Insights
        "insights.title": "Cyber Law Insights",
        "insights.subtitle": "Your expert source for analysis on digital law, privacy, and AI governance.",
        "insights.generate": "Generate AI Summary",
        "insights.generating": "Summarizing...",
        "insights.listen": "Listen to Summary",
        "insights.ask": "Ask AI about this article",
        "insights.summary_title": "AI Summary:",
        "insights.a1.title": "The GDPR Impact on AI Development",
        "insights.a1.snippet": "Examining the complex interplay between the EU's General Data Protection Regulation and artificial intelligence.",
        "insights.a1.content": "Two years after its full implementation, the GDPR continues to shape the digital landscape. For AI developers, the regulation presents a unique set of hurdles. The principles of data minimization and purpose limitation often conflict with the data-hungry nature of machine learning models. This article explores several key court rulings that have clarified the scope of 'legitimate interest' as a legal basis for processing data for AI training.",
        "insights.a2.title": "Digital Forensics in the Cloud",
        "insights.a2.snippet": "A deep dive into the legal complexities of conducting digital forensic investigations when data is stored across multiple jurisdictions.",
        "insights.a2.content": "Cloud computing has revolutionized data storage, but it has created a nightmare for digital forensic investigators. When a corporation's data is spread across servers in Ireland, Germany, and the United States, which jurisdiction's laws apply? The U.S. CLOUD Act was a significant attempt to address this, but it often clashes with data sovereignty laws in other nations.",
        "insights.a3.title": "Copyright and AI-Generated Art",
        "insights.a3.snippet": "The rise of generative AI models like DALL-E 2 and Midjourney has sparked a fierce debate in copyright law.",
        "insights.a3.content": "Recent decisions from the U.S. Copyright Office have consistently denied copyright protection to works generated solely by AI, stating that human authorship is a prerequisite. However, the line is blurring. What level of human input in prompting and curating AI output is sufficient to qualify as authorship? This article analyzes the 'work for hire' doctrine and its potential application to AI systems.",

        // Templates
        "templates.title": "Legal Templates Library",
        "templates.subtitle": "Access a collection of ready-to-use legal documents for various cyber law scenarios.",
        "templates.copy": "Copy to Clipboard",
        "templates.copied": "Copied!",
        "templates.customize": "Customize with Cylex AI",
        "templates.category.all": "All",
        "templates.cat.ip": "Intellectual Property",
        "templates.cat.privacy": "Data Privacy",
        "templates.cat.contracts": "Contracts & Agreements",
        
        "templates.t1.title": "Cease and Desist Letter",
        "templates.t1.desc": "A formal demand to stop an illegal activity, such as trademark or copyright infringement.",
        "templates.t1.content": "[Your Name]\n[Address]\n[Date]\n\nDear [Name],\n\nThis letter serves as a formal demand that you immediately CEASE AND DESIST all unauthorized use of [Your Company]'s intellectual property. It has come to our attention that you are using our material without consent. We demand you remove it immediately. Failure to comply will result in legal action.\n\nSincerely,\n[Your Name]",

        "templates.t2.title": "Privacy Policy",
        "templates.t2.desc": "A basic template for a website privacy policy outlining data collection and use.",
        "templates.t2.content": "PRIVACY POLICY\n\n[Your Company] collects data to improve our service. We may collect Personal Data (Name, Email) and Usage Data. We use this to maintain the Service and notify you of changes. We respect your data rights.",

        "templates.t3.title": "Non-Disclosure Agreement (NDA)",
        "templates.t3.desc": "A standard mutual NDA to protect confidential information between two parties.",
        "templates.t3.content": "MUTUAL NON-DISCLOSURE AGREEMENT\n\nThis Agreement is between [Party 1] and [Party 2]. 'Confidential Information' means any data proprietary to the disclosing party. Both parties agree not to disclose this information to third parties. This agreement survives for [Years] years.",

        "templates.t4.title": "Data Breach Notification",
        "templates.t4.desc": "A template for notifying affected individuals about a data breach.",
        "templates.t4.content": "NOTICE OF DATA INCIDENT\n\nDear [Name],\n\nWe are writing to inform you of a data security incident. On [Date], we discovered unauthorized access to our systems. Your personal information may have been involved. We are taking steps to secure our systems. Please remain vigilant.",

        // Labs
        "labs.title": "AI Labs",
        "labs.subtitle": "A glimpse into the future. Here we showcase our experimental projects at the bleeding edge of AI and law.",
        "labs.coming_soon": "Coming Soon",
        "labs.exp1.title": "Phishing Evidence Classifier",
        "labs.exp1.desc": "An experimental model that analyzes email headers, body content, and attachments to classify potential phishing attempts and automatically extract key evidence for legal action.",
        "labs.exp2.title": "Smart Contract Risk Scanner",
        "labs.exp2.desc": "Utilizes static and dynamic analysis to scan blockchain smart contracts for common vulnerabilities (e.g., reentrancy attacks) and potential legal ambiguities before deployment.",
        "labs.exp3.title": "Predictive E-Discovery Tagger",
        "labs.exp3.desc": "A proof-of-concept tool that uses natural language processing to predict the relevance of documents in large e-discovery datasets, aiming to significantly reduce manual review time.",
        "labs.exp4.title": "Deepfake Detection API",
        "labs.exp4.desc": "A research project focused on creating a service that can analyze video evidence to provide a probability score for deepfake manipulation, crucial for authenticating digital media.",
        "labs.status.experimental": "Experimental",
        "labs.status.development": "In Development",
        "labs.status.concept": "Concept",

        // Document Analyzer
        "analyzer.title": "AI Document Analyzer",
        "analyzer.subtitle": "Upload a legal document (.txt, .md) for risk and inconsistency analysis.",
        "analyzer.select": "Select a file",
        "analyzer.change": "Change file",
        "analyzer.btn": "Analyze Document",
        "analyzer.loading": "Analyzing Document",
        "analyzer.loading.desc": "Detecting risks and inconsistencies...",
        "analyzer.results": "Analysis Results:",

        // News Summarizer
        "summarizer.title": "Legal News Summarizer",
        "summarizer.subtitle": "Get AI-powered summaries of the latest legal news and rulings, with sources.",
        "summarizer.placeholder": "e.g., recent data privacy laws",
        "summarizer.btn": "Summarize",
        "summarizer.results": "Summary:",
        "summarizer.sources": "Sources:",

        // Legal Copilot
        "copilot.title": "AI Legal Copilot",
        "copilot.subtitle": "Describe your situation to receive a personalized, step-by-step action plan.",
        "copilot.label": "Case Details",
        "copilot.placeholder": "Describe the incident, parties involved, and your desired outcome. For example: 'I am a small business owner and I suspect a former employee stole our client list...'",
        "copilot.btn": "Generate Action Plan",
        "copilot.results": "Generated Action Plan:",
        "copilot.disclaimer": "Disclaimer: This is an AI-generated plan for informational purposes only and does not constitute legal advice.",

        // Case DNA
        "casedna.title": "AI Case DNA Analyzer",
        "casedna.subtitle": "Visually map your case by extracting timelines, entities, evidence, and liabilities.",
        "casedna.placeholder": "Describe the incident, upload a document, or paste text here...",
        "casedna.upload": "Upload Document (.txt, .md)",
        "casedna.or": "OR",
        "casedna.btn": "Analyze Case DNA",
        "casedna.map": "Case DNA Map",
        "casedna.timeline": "Timeline",
        "casedna.entities": "Key Entities",
        "casedna.evidence": "Evidence Patterns",
        "casedna.liabilities": "Potential Legal Liabilities",
        "casedna.modal.timeline": "Timeline Event Details",
        "casedna.modal.entity": "Entity Details",

        // Risk Meter
        "riskmeter.title": "AI Cyber Risk Meter",
        "riskmeter.subtitle": "Paste your privacy policy, terms of service, or contract text below for a risk assessment.",
        "riskmeter.placeholder": "Paste text here...",
        "riskmeter.btn": "Assess Risk",
        "riskmeter.results": "Risk Assessment Results",
        "riskmeter.level": "Overall Risk Level:",
        "riskmeter.risk": "Identified Risk",
        "riskmeter.rec": "Recommendation",

        // Precedent Predictor
        "predictor.title": "AI Precedent Predictor",
        "predictor.subtitle": "Analyze your case against historical data to predict likely outcomes and strategies.",
        "predictor.placeholder": "Describe your case here. Include key facts, parties involved, and the legal questions at hand...",
        "predictor.btn": "Predict Outcome",
        "predictor.dashboard": "Prediction Dashboard",
        "predictor.outcomes": "Predicted Outcomes",
        "predictor.sections": "Key Legal Sections",
        "predictor.strategies": "Suggested Strategies",
        "predictor.confidence": "Confidence",
        "predictor.likelihood": "Likelihood",
    },
    es: {
        "hero.title": "El Futuro de la Ley Encuentra la Inteligencia Cibernética",
        "hero.subtitle.1": "Su Caso, Nuestro Código.",
        "hero.subtitle.2": "Donde la Justicia Encuentra los Algoritmos.",
        "nav.home": "Inicio",
        "nav.templates": "Plantillas",
        "nav.knowledge": "Conocimiento",
        "nav.insights": "Perspectivas",
        "nav.labs": "Laboratorios",
        "nav.tools": "Herramientas",
        "nav.engage": "Interactuar",
        "nav.about": "Nosotros",
        "section.toolkit": "Inteligencia Legal de Próxima Generación",
        "section.toolkit.title": "Nuestro Kit Legal Impulsado por IA",
        "section.toolkit.desc": "Implementando redes neuronales avanzadas para decodificar complejidades legales.",
        "region.eu": "Unión Europea",
        "region.us": "Estados Unidos",
        "region.br": "Brasil",
        "region.in": "India",
        "region.jp": "Japón",
        "region.au": "Australia",
        "engage.title": "Centro de Participación",
        "engage.subtitle": "Interactúa con nuestras herramientas avanzadas de IA.",
        "engage.voice.title": "Consulta por Voz",
        "engage.voice.desc": "Hable directamente con Cylex para una consulta manos libres.",
        "engage.quiz.title": "¿Eres Experto en Ciberleyes?",
        "engage.quiz.desc": "Pon a prueba tus conocimientos con nuestro cuestionario generado por IA.",
        "engage.news.title": "Boletín Legal IA",
        "engage.news.desc": "Genere un boletín personalizado con las últimas actualizaciones legales.",
        "engage.back": "Volver",
        "voice.title": "Consulta de Voz IA",
        "voice.subtitle": "Hable directamente con Cylex para una consulta manos libres.",
        "voice.back": "Volver",
        "voice.status.connected": "Conectado",
        "voice.status.connecting": "Conectando...",
        "voice.status.error": "Error",
        "voice.status.disconnected": "Desconectado",
        "voice.btn.start": "Iniciar Consulta",
        "voice.btn.end": "Terminar Consulta",
        "voice.listening": "Cylex está escuchando...",
        "voice.live.disclaimer": "Esta es una consulta en vivo. Su micrófono está activo.",
        "quiz.title": "¿Eres Experto en Ciberleyes?",
        "quiz.subtitle": "Un cuestionario gamificado para probar tu experiencia.",
        "quiz.back": "Volver",
        "quiz.loading": "Generando su cuestionario...",
        "quiz.complete": "¡Cuestionario Completo!",
        "quiz.score": "Su puntuación",
        "quiz.play_again": "Jugar de Nuevo",
        "quiz.question_count": "Pregunta",
        "quiz.of": "de",
        "quiz.explanation": "Explicación:",
        "quiz.next": "Siguiente Pregunta",
        "quiz.finish": "Terminar",
        "quiz.start_prompt": "¿Listo para probar tu conocimiento?",
        "quiz.start_desc": "Obtén un cuestionario único generado por IA.",
        "quiz.start_btn": "Iniciar Cuestionario",
        "news.title": "Generador de Boletines Legales",
        "news.subtitle": "Obtenga un boletín legal personalizado para su región.",
        "news.back": "Volver",
        "news.placeholder": "ej., Unión Europea",
        "news.btn": "Generar",
        "news.loading": "Generando su boletín...",
        "news.result_title": "Su Boletín Personalizado",
        "news.sources": "Fuentes Utilizadas:",
        "templates.title": "Biblioteca de Plantillas",
        "templates.subtitle": "Acceda a documentos legales listos para usar.",
        "templates.copy": "Copiar",
        "templates.copied": "¡Copiado!",
        "templates.customize": "Personalizar",
        "templates.category.all": "Todo",
        "templates.cat.ip": "Propiedad Intelectual",
        "templates.cat.privacy": "Privacidad de Datos",
        "templates.cat.contracts": "Contratos",
        "templates.t1.title": "Carta de Cese y Desistimiento",
        "templates.t1.desc": "Demanda formal para detener una actividad ilegal.",
        "templates.t1.content": "[Su Nombre]\n[Dirección]\n[Fecha]\n\nEstimado [Nombre],\n\nEsta carta sirve como demanda formal para que CESE Y DESISTA inmediatamente todo uso no autorizado de la propiedad intelectual de [Su Empresa]. Exigimos que lo elimine de inmediato. El incumplimiento resultará en acciones legales.\n\nAtentamente,\n[Su Nombre]",
        "templates.t2.title": "Política de Privacidad",
        "templates.t2.desc": "Plantilla básica para la política de privacidad de un sitio web.",
        "templates.t2.content": "POLÍTICA DE PRIVACIDAD\n\n[Su Empresa] recopila datos para mejorar nuestro servicio. Podemos recopilar Datos Personales (Nombre, Email) y Datos de Uso. Respetamos sus derechos de datos.",
        "templates.t3.title": "Acuerdo de Confidencialidad (NDA)",
        "templates.t3.desc": "NDA mutuo estándar para proteger información confidencial.",
        "templates.t3.content": "ACUERDO DE CONFIDENCIALIDAD MUTUO\n\nEste Acuerdo es entre [Parte 1] y [Parte 2]. 'Información Confidencial' significa cualquier dato propietario de la parte reveladora. Ambas partes acuerdan no revelar esta información. Este acuerdo sobrevive por [Años] años.",
        "templates.t4.title": "Notificación de Violación de Datos",
        "templates.t4.desc": "Plantilla para notificar sobre una violación de datos.",
        "templates.t4.content": "AVISO DE INCIDENTE DE DATOS\n\nEstimado [Nombre],\n\nLe escribimos para informarle de un incidente de seguridad. El [Fecha], descubrimos un acceso no autorizado. Su información personal puede haber estado involucrada. Estamos tomando medidas.",
        "insights.a1.title": "Impacto del RGPD en la IA",
        "insights.a1.snippet": "Examinando la interacción entre el RGPD de la UE y la inteligencia artificial.",
        "insights.a1.content": "Dos años después de su implementación, el RGPD sigue dando forma al panorama digital. Para los desarrolladores de IA, presenta desafíos únicos. Los principios de minimización de datos a menudo entran en conflicto con el aprendizaje automático.",
        "insights.a2.title": "Forense Digital en la Nube",
        "insights.a2.snippet": "Complejidades legales de investigaciones forenses en la nube.",
        "insights.a2.content": "La computación en la nube ha revolucionado el almacenamiento, pero ha creado una pesadilla para los investigadores forenses. Cuando los datos están en varios países, ¿qué ley aplica?",
        "insights.a3.title": "Derechos de Autor y Arte IA",
        "insights.a3.snippet": "El auge de la IA generativa ha desatado un debate sobre derechos de autor.",
        "insights.a3.content": "Decisiones recientes han negado la protección de derechos de autor a obras generadas únicamente por IA. Sin embargo, la línea se está desdibujando.",
        "labs.title": "Laboratorios de IA",
        "labs.subtitle": "Un vistazo al futuro. Proyectos experimentales en la vanguardia de la IA y la ley.",
        "labs.coming_soon": "Próximamente",
        "labs.status.experimental": "Experimental",
        "labs.status.development": "En Desarrollo",
        "labs.status.concept": "Concepto",
        "tool.predictor": "Predictor de Precedentes",
        "tool.predictor.desc": "Pronostique resultados y optimice estrategias de litigio.",
        "tool.riskmeter": "Medidor de Riesgo Cibernético",
        "tool.riskmeter.desc": "Cuantifique la exposición legal en tiempo real.",
        "tool.casedna": "Analizador de ADN del Caso",
        "tool.casedna.desc": "Deconstruya casos complejos en líneas de tiempo visuales.",
        "tool.templates": "Plantillas Legales",
        "tool.templates.desc": "Genere y personalice documentos legales.",
        "tool.knowledge": "Centro de Conocimiento",
        "tool.knowledge.desc": "Navegue por las leyes cibernéticas globales.",
        "tool.analyzer": "Analizador de Documentos",
        "tool.analyzer.desc": "Detección automatizada de riesgos.",
        "tool.summarizer": "Resumidor de Noticias",
        "tool.summarizer.desc": "Manténgase al día con resúmenes en tiempo real.",
        "tool.copilot": "Copiloto Legal IA",
        "tool.copilot.desc": "Formule planes de acción estratégicos.",
        "chat.typing": "Cylex está escribiendo...",
        "analyzer.title": "Analizador de Documentos IA",
        "analyzer.subtitle": "Suba un documento legal para análisis de riesgos.",
        "analyzer.select": "Seleccionar archivo",
        "analyzer.change": "Cambiar archivo",
        "analyzer.btn": "Analizar Documento",
        "analyzer.loading": "Analizando Documento",
        "analyzer.loading.desc": "Detectando riesgos e inconsistencias...",
        "analyzer.results": "Resultados del Análisis:",
        "summarizer.title": "Resumidor de Noticias Legales",
        "summarizer.subtitle": "Obtenga resúmenes impulsados por IA de las últimas noticias legales.",
        "summarizer.placeholder": "ej., leyes de privacidad de datos recientes",
        "summarizer.btn": "Resumir",
        "summarizer.results": "Resumen:",
        "summarizer.sources": "Fuentes:",
        "copilot.title": "Copiloto Legal IA",
        "copilot.subtitle": "Describa su situación para recibir un plan de acción.",
        "copilot.label": "Detalles del Caso",
        "copilot.placeholder": "Describa el incidente, las partes involucradas y su resultado deseado...",
        "copilot.btn": "Generar Plan",
        "copilot.results": "Plan de Acción Generado:",
        "copilot.disclaimer": "Descargo de responsabilidad: Esto no constituye asesoramiento legal.",
        "casedna.title": "Analizador de ADN del Caso",
        "casedna.subtitle": "Mapee visualmente su caso extrayendo líneas de tiempo y entidades.",
        "casedna.placeholder": "Describa el incidente o suba un documento...",
        "casedna.upload": "Subir Documento",
        "casedna.or": "O",
        "casedna.btn": "Analizar ADN",
        "casedna.map": "Mapa de ADN del Caso",
        "casedna.timeline": "Línea de Tiempo",
        "casedna.entities": "Entidades Clave",
        "casedna.evidence": "Patrones de Evidencia",
        "casedna.liabilities": "Posibles Responsabilidades",
        "riskmeter.title": "Medidor de Riesgo Cibernético",
        "riskmeter.subtitle": "Pegue su política de privacidad o contrato para evaluar riesgos.",
        "riskmeter.placeholder": "Pegue el texto aquí...",
        "riskmeter.btn": "Evaluar Riesgo",
        "riskmeter.results": "Resultados de la Evaluación",
        "riskmeter.level": "Nivel de Riesgo General:",
        "riskmeter.risk": "Riesgo Identificado",
        "riskmeter.rec": "Recomendación",
        "predictor.title": "Predictor de Precedentes",
        "predictor.subtitle": "Analice su caso contra datos históricos.",
        "predictor.placeholder": "Describa su caso aquí...",
        "predictor.btn": "Predecir Resultado",
        "predictor.dashboard": "Panel de Predicción",
        "predictor.outcomes": "Resultados Predichos",
        "predictor.sections": "Secciones Legales Clave",
        "predictor.strategies": "Estrategias Sugeridas",
        "about.title": "Sobre Expertos Legales Cibernéticos",
        "about.desc": "Estamos en la intersección crítica de la ley y la tecnología. Nuestra firma se fundó sobre el principio de que la rápida evolución del mundo digital requiere un enfoque igualmente innovador de la práctica legal.",
        "about.timeline": "Una Historia Paralela: Ciberleyes e IA",
        "about.t.1986.title": "Ley de Fraude y Abuso Informático (CFAA)",
        "about.t.1986.desc": "La primera gran legislación estadounidense sobre delitos informáticos.",
        "about.t.1997.title": "Deep Blue derrota a Garry Kasparov",
        "about.t.1997.desc": "La victoria de la computadora de ajedrez de IBM marcó un hito en la IA.",
        "about.t.2000.title": "Ley E-SIGN",
        "about.t.2000.desc": "Legitimó las firmas electrónicas en EE. UU.",
        "about.t.2012.title": "AlexNet gana ImageNet",
        "about.t.2012.desc": "Modelo de aprendizaje profundo que revolucionó la visión por computadora.",
        "about.t.2016.title": "Reglamento General de Protección de Datos (RGPD)",
        "about.t.2016.desc": "La UE promulgó el RGPD, estableciendo un nuevo estándar global.",
        "about.t.2017.title": "Arquitectura Transformers",
        "about.t.2017.desc": "Investigadores de Google publican 'Attention Is All You Need'.",
        "about.t.2018.title": "Ley CLOUD",
        "about.t.2018.desc": "Ley de EE. UU. que permite a las fuerzas del orden obligar a las empresas a proporcionar datos.",
        "about.t.2022.title": "Lanzamiento de ChatGPT",
        "about.t.2022.desc": "El lanzamiento de ChatGPT por OpenAI llevó la IA generativa a la corriente principal.",
        "knowledge.title": "Centro de Conocimiento Legal",
        "knowledge.subtitle": "Explore descripciones generales de leyes cibernéticas.",
        "knowledge.back": "Volver a Regiones",
        "knowledge.overview": "Resumen Legal",
        "knowledge.fetch": "Buscando información legal...",
        "knowledge.sources": "Fuentes Utilizadas",
        "knowledge.disclaimer": "Descargo de responsabilidad: Solo para fines educativos.",
        "insights.title": "Perspectivas de Ciberleyes",
        "insights.subtitle": "Su fuente experta de análisis.",
        "insights.generate": "Generar Resumen IA",
        "insights.generating": "Resumiendo...",
        "insights.listen": "Escuchar Resumen",
        "insights.ask": "Preguntar a IA",
        "insights.summary_title": "Resumen IA:",
        "ticker.threat.1": "Detectada campaña activa de phishing dirigida a instituciones financieras.",
        "ticker.threat.2": "Nuevo exploit de día cero encontrado en software de servidor ampliamente utilizado.",
        "ticker.threat.3": "Ataque de ransomware interrumpe importante proveedor de atención médica.",
        "ticker.threat.4": "Violación de datos expone información personal de más de 1M de usuarios.",
        "ticker.threat.5": "Advertencia emitida por malware de espionaje patrocinado por el estado.",
        "ticker.insight.1": "La Corte Suprema dictamina sobre privacidad digital en computación en la nube.",
        "ticker.insight.2": "Nuevo precedente establecido para robo de PI en un caso de datos transfronterizos.",
        "ticker.insight.3": "Multa histórica del RGPD emitida por incumplimiento.",
        "ticker.insight.4": "Análisis: Fallo reciente sobre derechos de autor de contenido generado por IA.",
        "ticker.insight.5": "Tendencias de tecnología legal: Análisis predictivo en litigios.",
    },
    fr: {
        "hero.title": "L'Avenir du Droit Rencontre l'Intelligence",
        "hero.subtitle.1": "Votre Cas, Notre Code.",
        "hero.subtitle.2": "Où la Justice Rencontre les Algorithmes.",
        "nav.home": "Accueil",
        "nav.templates": "Modèles",
        "nav.knowledge": "Connaissances",
        "nav.insights": "Perspectives",
        "nav.labs": "Laboratoires",
        "nav.tools": "Outils",
        "nav.engage": "Engager",
        "nav.about": "À Propos",
        "section.toolkit": "Intelligence Juridique de Nouvelle Génération",
        "section.toolkit.title": "Notre Boîte à Outils Juridique IA",
        "section.toolkit.desc": "Déployer des réseaux neuronaux avancés pour décoder les complexités juridiques.",
        "region.eu": "Union Européenne",
        "region.us": "États-Unis",
        "region.br": "Brésil",
        "region.in": "Inde",
        "region.jp": "Japon",
        "region.au": "Australie",
        "engage.title": "Centre d'Engagement",
        "engage.subtitle": "Interagissez avec nos outils IA avancés.",
        "engage.voice.title": "Consultation Vocale",
        "engage.voice.desc": "Parlez directement avec Cylex pour une consultation mains libres.",
        "engage.quiz.title": "Expert en Cyber-Droit ?",
        "engage.quiz.desc": "Testez vos connaissances avec notre quiz généré par IA.",
        "engage.news.title": "Newsletter Juridique IA",
        "engage.news.desc": "Générez une newsletter personnalisée avec les dernières mises à jour.",
        "engage.back": "Retour",
        "voice.title": "Consultation Vocale IA",
        "voice.subtitle": "Parlez directement avec Cylex.",
        "voice.back": "Retour",
        "voice.status.connected": "Connecté",
        "voice.status.connecting": "Connexion...",
        "voice.status.error": "Erreur",
        "voice.status.disconnected": "Déconnecté",
        "voice.btn.start": "Démarrer Consultation",
        "voice.btn.end": "Terminer Consultation",
        "voice.listening": "Cylex écoute...",
        "voice.live.disclaimer": "Ceci est une consultation en direct. Votre micro est actif.",
        "quiz.title": "Expert en Cyber-Droit ?",
        "quiz.subtitle": "Un quiz ludique pour tester votre expertise.",
        "quiz.back": "Retour",
        "quiz.loading": "Génération du quiz...",
        "quiz.complete": "Quiz Terminé !",
        "quiz.score": "Votre score",
        "quiz.play_again": "Rejouer",
        "quiz.question_count": "Question",
        "quiz.of": "sur",
        "quiz.explanation": "Explication :",
        "quiz.next": "Question Suivante",
        "quiz.finish": "Terminer",
        "quiz.start_prompt": "Prêt à tester vos connaissances ?",
        "quiz.start_desc": "Obtenez un quiz unique généré par IA.",
        "quiz.start_btn": "Démarrer le Quiz",
        "news.title": "Générateur de Newsletter",
        "news.subtitle": "Obtenez une newsletter juridique personnalisée.",
        "news.back": "Retour",
        "news.placeholder": "ex., Union Européenne",
        "news.btn": "Générer",
        "news.loading": "Génération de la newsletter...",
        "news.result_title": "Votre Newsletter Personnalisée",
        "news.sources": "Sources Utilisées :",
        "templates.title": "Bibliothèque de Modèles",
        "templates.subtitle": "Accédez à des documents juridiques prêts à l'emploi.",
        "templates.copy": "Copier",
        "templates.copied": "Copié !",
        "templates.customize": "Personnaliser",
        "templates.category.all": "Tout",
        "templates.cat.ip": "Propriété Intellectuelle",
        "templates.cat.privacy": "Confidentialité",
        "templates.cat.contracts": "Contrats",
        "templates.t1.title": "Lettre de Mise en Demeure",
        "templates.t1.desc": "Demande formelle de cesser une activité illégale.",
        "templates.t1.content": "[Votre Nom]\n[Adresse]\n[Date]\n\nCher [Nom],\n\nCette lettre sert de mise en demeure formelle de CESSER IMMÉDIATEMENT toute utilisation non autorisée de la propriété intellectuelle de [Votre Entreprise]. Nous exigeons que vous la retiriez immédiatement.\n\nCordialement,\n[Votre Nom]",
        "templates.t2.title": "Politique de Confidentialité",
        "templates.t2.desc": "Modèle de base pour la politique de confidentialité d'un site.",
        "templates.t2.content": "POLITIQUE DE CONFIDENTIALITÉ\n\n[Votre Entreprise] collecte des données pour améliorer notre service. Nous pouvons collecter des Données Personnelles et des Données d'Utilisation. Nous respectons vos droits.",
        "templates.t3.title": "Accord de Non-Divulgation (NDA)",
        "templates.t3.desc": "NDA mutuel pour protéger les informations confidentielles.",
        "templates.t3.content": "ACCORD DE NON-DIVULGATION MUTUEL\n\nCet Accord est entre [Partie 1] et [Partie 2]. Les deux parties conviennent de ne pas divulguer les informations confidentielles.",
        "templates.t4.title": "Notification de Violation de Données",
        "templates.t4.desc": "Modèle pour notifier une violation de données.",
        "templates.t4.content": "AVIS D'INCIDENT DE DONNÉES\n\nCher [Nom],\n\nNous vous informons d'un incident de sécurité. Le [Date], nous avons découvert un accès non autorisé. Vos informations personnelles peuvent être concernées.",
        "insights.a1.title": "Impact du RGPD sur l'IA",
        "insights.a1.snippet": "Examen de l'interaction entre le RGPD et l'IA.",
        "insights.a1.content": "Le RGPD continue de façonner le paysage numérique. Pour les développeurs d'IA, il présente des défis uniques concernant la minimisation des données.",
        "insights.a2.title": "Forensique Numérique dans le Cloud",
        "insights.a2.snippet": "Complexités juridiques des enquêtes dans le cloud.",
        "insights.a2.content": "Le cloud a révolutionné le stockage mais compliqué les enquêtes. Quelle loi s'applique quand les données sont partout ?",
        "insights.a3.title": "Droit d'Auteur et Art IA",
        "insights.a3.snippet": "Le débat sur le droit d'auteur et l'IA générative.",
        "insights.a3.content": "Les décisions récentes refusent le droit d'auteur aux œuvres purement IA. La ligne devient floue.",
        "labs.title": "Laboratoires IA",
        "labs.subtitle": "Un aperçu du futur. Projets expérimentaux à la pointe de l'IA et du droit.",
        "labs.coming_soon": "Bientôt",
        "labs.status.experimental": "Expérimental",
        "labs.status.development": "En Développement",
        "labs.status.concept": "Concept",
        "tool.predictor": "Prédicteur de Précédents",
        "tool.predictor.desc": "Prévoyez les résultats et optimisez les stratégies.",
        "tool.riskmeter": "Compteur de Risque Cyber",
        "tool.riskmeter.desc": "Quantifiez l'exposition juridique en temps réel.",
        "tool.casedna": "Analyseur d'ADN de Cas",
        "tool.casedna.desc": "Déconstruisez les cas complexes.",
        "tool.templates": "Modèles Juridiques",
        "tool.templates.desc": "Générez et personnalisez des documents.",
        "tool.knowledge": "Pôle de Connaissances",
        "tool.knowledge.desc": "Naviguez dans les lois mondiales.",
        "tool.analyzer": "Analyseur de Documents",
        "tool.analyzer.desc": "Détection automatisée des risques.",
        "tool.summarizer": "Résumé d'Actualités",
        "tool.summarizer.desc": "Restez informé en temps réel.",
        "tool.copilot": "Copilote Juridique IA",
        "tool.copilot.desc": "Formulez des plans d'action stratégiques.",
        "chat.typing": "Cylex écrit...",
        "analyzer.title": "Analyseur de Documents IA",
        "analyzer.subtitle": "Téléchargez un document pour analyse.",
        "analyzer.select": "Choisir un fichier",
        "analyzer.change": "Changer",
        "analyzer.btn": "Analyser",
        "analyzer.loading": "Analyse en cours",
        "analyzer.loading.desc": "Détection des risques...",
        "analyzer.results": "Résultats :",
        "summarizer.title": "Résumé d'Actualités Juridiques",
        "summarizer.subtitle": "Résumés IA des dernières actualités.",
        "summarizer.placeholder": "ex., lois sur la vie privée",
        "summarizer.btn": "Résumer",
        "summarizer.results": "Résumé :",
        "summarizer.sources": "Sources :",
        "copilot.title": "Copilote Juridique IA",
        "copilot.subtitle": "Décrivez votre situation pour un plan d'action.",
        "copilot.label": "Détails du Cas",
        "copilot.placeholder": "Décrivez l'incident...",
        "copilot.btn": "Générer le Plan",
        "copilot.results": "Plan d'Action :",
        "copilot.disclaimer": "Avis : Ceci ne constitue pas un avis juridique.",
        "casedna.title": "Analyseur d'ADN de Cas",
        "casedna.subtitle": "Cartographiez visuellement votre cas.",
        "casedna.placeholder": "Décrivez l'incident...",
        "casedna.upload": "Télécharger Document",
        "casedna.or": "OU",
        "casedna.btn": "Analyser ADN",
        "casedna.map": "Carte ADN du Cas",
        "casedna.timeline": "Chronologie",
        "casedna.entities": "Entités Clés",
        "casedna.evidence": "Modèles de Preuve",
        "casedna.liabilities": "Responsabilités Potentielles",
        "riskmeter.title": "Compteur de Risque Cyber",
        "riskmeter.subtitle": "Collez votre politique pour évaluer les risques.",
        "riskmeter.placeholder": "Collez le texte ici...",
        "riskmeter.btn": "Évaluer",
        "riskmeter.results": "Résultats de l'Évaluation",
        "riskmeter.level": "Niveau de Risque :",
        "riskmeter.risk": "Risque Identifié",
        "riskmeter.rec": "Recommandation",
        "predictor.title": "Prédicteur de Précédents",
        "predictor.subtitle": "Analysez votre cas avec des données historiques.",
        "predictor.placeholder": "Décrivez votre cas...",
        "predictor.btn": "Prédire",
        "predictor.dashboard": "Tableau de Bord",
        "predictor.outcomes": "Résultats Prévus",
        "predictor.sections": "Sections Clés",
        "predictor.strategies": "Stratégies Suggérées",
        "about.title": "À Propos",
        "about.desc": "L'intersection du droit et de la technologie.",
        "about.timeline": "Une Histoire Parallèle",
        "about.t.1986.title": "Computer Fraud and Abuse Act (CFAA)",
        "about.t.1986.desc": "La première législation américaine majeure sur la cybercriminalité.",
        "about.t.1997.title": "Deep Blue bat Garry Kasparov",
        "about.t.1997.desc": "La victoire de l'ordinateur d'échecs d'IBM a marqué une étape majeure.",
        "about.t.2000.title": "Loi E-SIGN",
        "about.t.2000.desc": "Légalisation des signatures électroniques aux États-Unis.",
        "about.t.2012.title": "AlexNet remporte ImageNet",
        "about.t.2012.desc": "Modèle d'apprentissage profond révolutionnant la vision par ordinateur.",
        "about.t.2016.title": "Règlement Général sur la Protection des Données (RGPD)",
        "about.t.2016.desc": "L'UE a promulgué le RGPD, établissant une nouvelle norme mondiale.",
        "about.t.2017.title": "Architecture Transformers",
        "about.t.2017.desc": "Les chercheurs de Google publient 'Attention Is All You Need'.",
        "about.t.2018.title": "Loi CLOUD",
        "about.t.2018.desc": "Loi américaine permettant d'obliger les entreprises à fournir des données.",
        "about.t.2022.title": "Lancement de ChatGPT",
        "about.t.2022.desc": "Le lancement de ChatGPT par OpenAI a démocratisé l'IA générative.",
        "knowledge.title": "Pôle de Connaissances",
        "knowledge.subtitle": "Explorez les lois mondiales.",
        "knowledge.back": "Retour",
        "knowledge.overview": "Aperçu Juridique",
        "knowledge.fetch": "Récupération des infos...",
        "knowledge.sources": "Sources",
        "knowledge.disclaimer": "Avis : À des fins éducatives seulement.",
        "insights.title": "Perspectives",
        "insights.subtitle": "Votre source experte.",
        "insights.generate": "Générer Résumé",
        "insights.generating": "En cours...",
        "insights.listen": "Écouter",
        "insights.ask": "Demander à l'IA",
        "insights.summary_title": "Résumé IA :",
        "ticker.threat.1": "Campagne de phishing active ciblant les institutions financières détectée.",
        "ticker.threat.2": "Nouvel exploit Zero-Day trouvé dans un logiciel serveur largement utilisé.",
        "ticker.threat.3": "Une attaque par ransomware perturbe un important prestataire de soins de santé.",
        "ticker.threat.4": "Une violation de données expose les informations personnelles de plus d'un million d'utilisateurs.",
        "ticker.threat.5": "Avertissement émis concernant un logiciel espion parrainé par l'État.",
        "ticker.insight.1": "La Cour suprême statue sur la confidentialité numérique dans le cloud computing.",
        "ticker.insight.2": "Nouveau précédent établi pour le vol de propriété intellectuelle dans une affaire de données transfrontalières.",
        "ticker.insight.3": "Amende historique du RGPD pour non-conformité.",
        "ticker.insight.4": "Analyse : Décision récente sur le droit d'auteur du contenu généré par l'IA.",
        "ticker.insight.5": "Tendances Legal Tech : Analyse prédictive dans les litiges.",
    },
    de: {
        "hero.title": "Die Zukunft des Rechts trifft Cyber-Intelligenz",
        "hero.subtitle.1": "Ihr Fall, Unser Code.",
        "hero.subtitle.2": "Wo Gerechtigkeit auf Algorithmen trifft.",
        "nav.home": "Start",
        "nav.templates": "Vorlagen",
        "nav.knowledge": "Wissen",
        "nav.insights": "Einblicke",
        "nav.labs": "KI-Labore",
        "nav.tools": "Werkzeuge",
        "nav.engage": "Engagement",
        "nav.about": "Über uns",
        "section.toolkit": "Rechtsintelligenz der Nächsten Generation",
        "section.toolkit.title": "Unser KI-gestütztes Rechts-Toolkit",
        "section.toolkit.desc": "Einsatz fortschrittlicher neuronaler Netze zur Entschlüsselung rechtlicher Komplexität.",
        "region.eu": "Europäische Union",
        "region.us": "Vereinigte Staaten",
        "region.br": "Brasilien",
        "region.in": "Indien",
        "region.jp": "Japan",
        "region.au": "Australien",
        "engage.title": "Engagement-Hub",
        "engage.subtitle": "Interagieren Sie mit unseren KI-Tools.",
        "engage.voice.title": "Sprachberatung",
        "engage.voice.desc": "Sprechen Sie direkt mit Cylex für eine freihändige Beratung.",
        "engage.quiz.title": "Cyber-Recht Experte?",
        "engage.quiz.desc": "Testen Sie Ihr Wissen mit unserem KI-generierten Quiz.",
        "engage.news.title": "KI-Rechtsnewsletter",
        "engage.news.desc": "Erstellen Sie einen personalisierten Newsletter mit den neuesten Updates.",
        "engage.back": "Zurück",
        "voice.title": "KI-Sprachberatung",
        "voice.subtitle": "Sprechen Sie direkt mit Cylex.",
        "voice.back": "Zurück",
        "voice.status.connected": "Verbunden",
        "voice.status.connecting": "Verbinde...",
        "voice.status.error": "Fehler",
        "voice.status.disconnected": "Getrennt",
        "voice.btn.start": "Beratung Starten",
        "voice.btn.end": "Beratung Beenden",
        "voice.listening": "Cylex hört zu...",
        "voice.live.disclaimer": "Dies ist eine Live-Beratung. Ihr Mikrofon ist aktiv.",
        "quiz.title": "Cyber-Recht Experte?",
        "quiz.subtitle": "Ein spielerisches Quiz.",
        "quiz.back": "Zurück",
        "quiz.loading": "Erstelle Quiz...",
        "quiz.complete": "Quiz Beendet!",
        "quiz.score": "Ihr Ergebnis",
        "quiz.play_again": "Nochmal Spielen",
        "quiz.question_count": "Frage",
        "quiz.of": "von",
        "quiz.explanation": "Erklärung:",
        "quiz.next": "Nächste Frage",
        "quiz.finish": "Beenden",
        "quiz.start_prompt": "Bereit, Ihr Wissen zu testen?",
        "quiz.start_desc": "Holen Sie sich ein einzigartiges KI-Quiz.",
        "quiz.start_btn": "Quiz Starten",
        "news.title": "Newsletter-Generator",
        "news.subtitle": "Holen Sie sich einen personalisierten Rechtsnewsletter.",
        "news.back": "Zurück",
        "news.placeholder": "z.B. Europäische Union",
        "news.btn": "Generieren",
        "news.loading": "Erstelle Newsletter...",
        "news.result_title": "Ihr Personalisierter Newsletter",
        "news.sources": "Verwendete Quellen:",
        "templates.title": "Vorlagen-Bibliothek",
        "templates.subtitle": "Zugriff auf fertige Rechtsdokumente.",
        "templates.copy": "Kopieren",
        "templates.copied": "Kopiert!",
        "templates.customize": "Anpassen",
        "templates.category.all": "Alle",
        "templates.cat.ip": "Geistiges Eigentum",
        "templates.cat.privacy": "Datenschutz",
        "templates.cat.contracts": "Verträge",
        "templates.t1.title": "Abmahnung",
        "templates.t1.desc": "Formelle Aufforderung, eine illegale Handlung zu unterlassen.",
        "templates.t1.content": "[Ihr Name]\n[Adresse]\n[Datum]\n\nSehr geehrte(r) [Name],\n\nHiermit fordern wir Sie formell auf, jegliche unbefugte Nutzung des geistigen Eigentums von [Ihre Firma] SOFORT ZU UNTERLASSEN. Wir fordern Sie auf, es sofort zu entfernen.\n\nMit freundlichen Grüßen,\n[Ihr Name]",
        "templates.t2.title": "Datenschutzerklärung",
        "templates.t2.desc": "Vorlage für eine Website-Datenschutzerklärung.",
        "templates.t2.content": "DATENSCHUTZERKLÄRUNG\n\n[Ihre Firma] sammelt Daten, um unseren Service zu verbessern. Wir können personenbezogene Daten und Nutzungsdaten sammeln.",
        "templates.t3.title": "Geheimhaltungsvereinbarung (NDA)",
        "templates.t3.desc": "Standard-NDA zum Schutz vertraulicher Informationen.",
        "templates.t3.content": "GEHEIMHALTUNGSVEREINBARUNG\n\nDiese Vereinbarung besteht zwischen [Partei 1] und [Partei 2]. Beide Parteien verpflichten sich, vertrauliche Informationen nicht an Dritte weiterzugeben.",
        "templates.t4.title": "Benachrichtigung über Datenpanne",
        "templates.t4.desc": "Vorlage zur Benachrichtigung über eine Datenpanne.",
        "templates.t4.content": "BENACHRICHTIGUNG ÜBER DATENVORFALL\n\nSehr geehrte(r) [Name],\n\nwir informieren Sie über einen Sicherheitsvorfall. Am [Datum] entdeckten wir unbefugten Zugriff.",
        "insights.a1.title": "DSGVO und KI-Entwicklung",
        "insights.a1.snippet": "Untersuchung des Zusammenspiels von DSGVO und KI.",
        "insights.a1.content": "Die DSGVO prägt weiterhin die digitale Landschaft. Für KI-Entwickler stellt sie besondere Herausforderungen dar.",
        "insights.a2.title": "Digitale Forensik in der Cloud",
        "insights.a2.snippet": "Rechtliche Komplexität von Cloud-Ermittlungen.",
        "insights.a2.content": "Cloud Computing hat die Datenspeicherung revolutioniert, aber Ermittlungen erschwert. Welches Recht gilt?",
        "insights.a3.title": "Urheberrecht und KI-Kunst",
        "insights.a3.snippet": "Die Debatte über Urheberrecht und generative KI.",
        "insights.a3.content": "Jüngste Entscheidungen verweigern rein KI-generierten Werken den Urheberrechtsschutz.",
        "labs.title": "KI-Labore",
        "labs.subtitle": "Ein Blick in die Zukunft.",
        "labs.coming_soon": "Demnächst",
        "labs.status.experimental": "Experimentell",
        "labs.status.development": "In Entwicklung",
        "labs.status.concept": "Konzept",
        "tool.predictor": "Präzedenzfall-Prognose",
        "tool.predictor.desc": "Prognostizieren Sie Ergebnisse.",
        "tool.riskmeter": "Cyber-Risikometer",
        "tool.riskmeter.desc": "Quantifizieren Sie rechtliche Risiken.",
        "tool.casedna": "Fall-DNA-Analyse",
        "tool.casedna.desc": "Komplexe Fälle zerlegen.",
        "tool.templates": "Rechtsvorlagen",
        "tool.templates.desc": "Dokumente erstellen.",
        "tool.knowledge": "Wissenszentrum",
        "tool.knowledge.desc": "Globale Cyber-Gesetze.",
        "tool.analyzer": "Dokumentenanalyse",
        "tool.analyzer.desc": "Automatisierte Risikoerkennung.",
        "tool.summarizer": "News-Zusammenfassung",
        "tool.summarizer.desc": "Bleiben Sie auf dem Laufenden.",
        "tool.copilot": "Rechts-Copilot",
        "tool.copilot.desc": "Strategische Pläne formulieren.",
        "chat.typing": "Cylex schreibt...",
        "analyzer.title": "KI-Dokumentenanalyse",
        "analyzer.subtitle": "Laden Sie ein Dokument zur Analyse hoch.",
        "analyzer.select": "Datei auswählen",
        "analyzer.change": "Ändern",
        "analyzer.btn": "Analysieren",
        "analyzer.loading": "Analysiere...",
        "analyzer.loading.desc": "Prüfe auf Risiken...",
        "analyzer.results": "Ergebnisse:",
        "summarizer.title": "Rechts-News Zusammenfassung",
        "summarizer.subtitle": "KI-Zusammenfassungen aktueller Nachrichten.",
        "summarizer.placeholder": "z.B. neue Datenschutzgesetze",
        "summarizer.btn": "Zusammenfassen",
        "summarizer.results": "Zusammenfassung:",
        "summarizer.sources": "Quellen:",
        "copilot.title": "KI-Rechts-Copilot",
        "copilot.subtitle": "Beschreiben Sie Ihre Situation.",
        "copilot.label": "Falldetails",
        "copilot.placeholder": "Beschreiben Sie den Vorfall...",
        "copilot.btn": "Plan Erstellen",
        "copilot.results": "Aktionsplan:",
        "copilot.disclaimer": "Hinweis: Keine Rechtsberatung.",
        "casedna.title": "Fall-DNA-Analyse",
        "casedna.subtitle": "Visualisieren Sie Ihren Fall.",
        "casedna.placeholder": "Beschreiben Sie den Vorfall...",
        "casedna.upload": "Dokument hochladen",
        "casedna.or": "ODER",
        "casedna.btn": "Analysieren",
        "casedna.map": "Fall-DNA-Karte",
        "casedna.timeline": "Zeitlinie",
        "casedna.entities": "Wichtige Entitäten",
        "casedna.evidence": "Beweismuster",
        "casedna.liabilities": "Haftung",
        "riskmeter.title": "Cyber-Risikometer",
        "riskmeter.subtitle": "Text zur Bewertung einfügen.",
        "riskmeter.placeholder": "Text hier einfügen...",
        "riskmeter.btn": "Bewerten",
        "riskmeter.results": "Bewertungsergebnisse",
        "riskmeter.level": "Risikostufe:",
        "riskmeter.risk": "Identifiziertes Risiko",
        "riskmeter.rec": "Empfehlung",
        "predictor.title": "Präzedenzfall-Prognose",
        "predictor.subtitle": "Fallanalyse mit historischen Daten.",
        "predictor.placeholder": "Fall beschreiben...",
        "predictor.btn": "Vorhersagen",
        "predictor.dashboard": "Prognose-Dashboard",
        "predictor.outcomes": "Ergebnisse",
        "predictor.sections": "Rechtsbereiche",
        "predictor.strategies": "Strategien",
        "about.title": "Über Uns",
        "about.desc": "Schnittstelle von Recht und Technologie.",
        "about.timeline": "Eine parallele Geschichte",
        "about.t.1986.title": "Computer Fraud and Abuse Act (CFAA)",
        "about.t.1986.desc": "Das erste große US-Gesetz gegen Computerkriminalität.",
        "about.t.1997.title": "Deep Blue besiegt Garry Kasparov",
        "about.t.1997.desc": "Der Sieg des Schachcomputers von IBM war ein Meilenstein der KI.",
        "about.t.2000.title": "E-SIGN Act",
        "about.t.2000.desc": "Legalisierte elektronische Signaturen in den USA.",
        "about.t.2012.title": "AlexNet gewinnt ImageNet",
        "about.t.2012.desc": "Deep Learning Modell, das Computer Vision revolutionierte.",
        "about.t.2016.title": "Datenschutz-Grundverordnung (DSGVO)",
        "about.t.2016.desc": "Die EU erließ die DSGVO und setzte einen neuen globalen Standard.",
        "about.t.2017.title": "Transformer-Architektur",
        "about.t.2017.desc": "Google-Forscher veröffentlichen 'Attention Is All You Need'.",
        "about.t.2018.title": "CLOUD Act",
        "about.t.2018.desc": "US-Gesetz zur Datenherausgabe durch Tech-Firmen.",
        "about.t.2022.title": "Start von ChatGPT",
        "about.t.2022.desc": "OpenAIs ChatGPT machte generative KI massentauglich.",
        "knowledge.title": "Wissenszentrum",
        "knowledge.subtitle": "Erkunden Sie Cyber-Gesetze.",
        "knowledge.back": "Zurück",
        "knowledge.overview": "Rechtsüberblick",
        "knowledge.fetch": "Lade Informationen...",
        "knowledge.sources": "Quellen",
        "knowledge.disclaimer": "Hinweis: Nur zu Bildungszwecken.",
        "insights.title": "Einblicke",
        "insights.subtitle": "Ihre Expertenquelle.",
        "insights.generate": "Zusammenfassen",
        "insights.generating": "Arbeite...",
        "insights.listen": "Anhören",
        "insights.ask": "KI fragen",
        "insights.summary_title": "KI-Zusammenfassung:",
        "ticker.threat.1": "Aktive Phishing-Kampagne gegen Finanzinstitute entdeckt.",
        "ticker.threat.2": "Neuer Zero-Day-Exploit in weit verbreiteter Serversoftware gefunden.",
        "ticker.threat.3": "Ransomware-Angriff stört großen Gesundheitsdienstleister.",
        "ticker.threat.4": "Datenpanne legt persönliche Daten von über 1 Mio. Nutzern offen.",
        "ticker.threat.5": "Warnung vor staatlich geförderter Spionage-Malware ausgegeben.",
        "ticker.insight.1": "Oberster Gerichtshof entscheidet über digitalen Datenschutz beim Cloud-Computing.",
        "ticker.insight.2": "Neuer Präzedenzfall für IP-Diebstahl in grenzüberschreitendem Datenfall.",
        "ticker.insight.3": "Wegweisendes DSGVO-Bußgeld wegen Nichteinhaltung verhängt.",
        "ticker.insight.4": "Analyse: Jüngstes Urteil zum Urheberrecht von KI-generierten Inhalten.",
        "ticker.insight.5": "Legal Tech Trends: Predictive Analytics in Rechtsstreitigkeiten.",
    },
    ja: {
        "hero.title": "法の未来とサイバーインテリジェンスの融合",
        "hero.subtitle.1": "あなたの事件、私たちのコード。",
        "hero.subtitle.2": "正義とアルゴリズムが出会う場所。",
        "nav.home": "ホーム",
        "nav.templates": "テンプレート",
        "nav.knowledge": "知識ハブ",
        "nav.insights": "洞察",
        "nav.labs": "AIラボ",
        "nav.tools": "ツール",
        "nav.engage": "エンゲージ",
        "nav.about": "私たちについて",
        "section.toolkit": "次世代リーガルインテリジェンス",
        "section.toolkit.title": "AI搭載リーガルツールキット",
        "section.toolkit.desc": "高度なニューラルネットワークを展開して法的複雑さを解読します。",
        "region.eu": "欧州連合",
        "region.us": "米国",
        "region.br": "ブラジル",
        "region.in": "インド",
        "region.jp": "日本",
        "region.au": "オーストラリア",
        "engage.title": "エンゲージメントハブ",
        "engage.subtitle": "高度なAIツールと対話します。",
        "engage.voice.title": "音声相談",
        "engage.voice.desc": "Cylexと直接話してハンズフリー相談。",
        "engage.quiz.title": "サイバー法クイズ",
        "engage.quiz.desc": "AI生成のクイズで知識をテスト。",
        "engage.news.title": "AI法務ニュースレター",
        "engage.news.desc": "パーソナライズされたニュースレターを作成。",
        "engage.back": "戻る",
        "voice.title": "AI音声相談",
        "voice.subtitle": "Cylexと直接話す。",
        "voice.back": "戻る",
        "voice.status.connected": "接続済み",
        "voice.status.connecting": "接続中...",
        "voice.status.error": "エラー",
        "voice.status.disconnected": "切断",
        "voice.btn.start": "相談開始",
        "voice.btn.end": "相談終了",
        "voice.listening": "Cylexが聞いています...",
        "voice.live.disclaimer": "これはライブ相談です。マイクはアクティブです。",
        "quiz.title": "サイバー法クイズ",
        "quiz.subtitle": "専門知識をテストするゲーム。",
        "quiz.back": "戻る",
        "quiz.loading": "クイズを作成中...",
        "quiz.complete": "クイズ完了！",
        "quiz.score": "あなたのスコア",
        "quiz.play_again": "もう一度プレイ",
        "quiz.question_count": "質問",
        "quiz.of": "/",
        "quiz.explanation": "解説：",
        "quiz.next": "次の質問",
        "quiz.finish": "終了",
        "quiz.start_prompt": "知識をテストしますか？",
        "quiz.start_desc": "ユニークなAIクイズを取得。",
        "quiz.start_btn": "クイズ開始",
        "news.title": "ニュースレター作成",
        "news.subtitle": "法務ニュースレターを取得。",
        "news.back": "戻る",
        "news.placeholder": "例：欧州連合",
        "news.btn": "作成",
        "news.loading": "作成中...",
        "news.result_title": "あなたのニュースレター",
        "news.sources": "使用されたソース：",
        "templates.title": "テンプレートライブラリ",
        "templates.subtitle": "すぐに使える法的文書コレクション。",
        "templates.copy": "コピー",
        "templates.copied": "完了！",
        "templates.customize": "カスタマイズ",
        "templates.category.all": "すべて",
        "templates.cat.ip": "知的財産",
        "templates.cat.privacy": "データプライバシー",
        "templates.cat.contracts": "契約",
        "templates.t1.title": "警告書",
        "templates.t1.desc": "違法行為の停止を求める正式な要求。",
        "templates.t1.content": "[あなたの名前]\n[住所]\n[日付]\n\n[名前] 様\n\n本書簡は、[あなたの会社]の知的財産の無断使用を直ちに停止することを求める正式な要求です。直ちに削除することを要求します。\n\n敬具\n[あなたの名前]",
        "templates.t2.title": "プライバシーポリシー",
        "templates.t2.desc": "Webサイトのプライバシーポリシーの基本テンプレート。",
        "templates.t2.content": "プライバシーポリシー\n\n[あなたの会社]はサービス向上のためにデータを収集します。個人データや利用データを収集する場合があります。",
        "templates.t3.title": "秘密保持契約 (NDA)",
        "templates.t3.desc": "機密情報を保護するための標準的なNDA。",
        "templates.t3.content": "秘密保持契約\n\n本契約は[甲]と[乙]の間で締結されます。両当事者は、機密情報を第三者に開示しないことに同意します。",
        "templates.t4.title": "データ侵害通知",
        "templates.t4.desc": "データ侵害について通知するためのテンプレート。",
        "templates.t4.content": "データインシデントに関する通知\n\n[名前] 様\n\nセキュリティインシデントについてお知らせします。[日付]に不正アクセスが発覚しました。あなたの個人情報が含まれている可能性があります。",
        "insights.a1.title": "GDPRのAI開発への影響",
        "insights.a1.snippet": "GDPRとAIの相互作用の検証。",
        "insights.a1.content": "GDPRはデジタル環境を形成し続けています。AI開発者にとって、データの最小化などの原則は課題となります。",
        "insights.a2.title": "クラウドにおけるデジタルフォレンジック",
        "insights.a2.snippet": "クラウド調査の法的複雑性。",
        "insights.a2.content": "クラウドコンピューティングは調査を複雑にしました。データが複数の国にある場合、どの法律が適用されるのでしょうか？",
        "insights.a3.title": "著作権とAIアート",
        "insights.a3.snippet": "生成AIと著作権法の議論。",
        "insights.a3.content": "最近の決定では、AIのみによって生成された作品への著作権保護が否定されています。",
        "labs.title": "AIラボ",
        "labs.subtitle": "未来への一瞥。",
        "labs.coming_soon": "近日公開",
        "labs.status.experimental": "実験的",
        "labs.status.development": "開発中",
        "labs.status.concept": "コンセプト",
        "tool.predictor": "判例予測",
        "tool.predictor.desc": "結果を予測し戦略を最適化。",
        "tool.riskmeter": "サイバーリスクメーター",
        "tool.riskmeter.desc": "法的リスクを定量化。",
        "tool.casedna": "事件DNA分析",
        "tool.casedna.desc": "複雑な事件を分解。",
        "tool.templates": "法的テンプレート",
        "tool.templates.desc": "文書を作成・カスタマイズ。",
        "tool.knowledge": "知識ハブ",
        "tool.knowledge.desc": "世界のサイバー法をナビゲート。",
        "tool.analyzer": "文書分析",
        "tool.analyzer.desc": "リスクの自動検出。",
        "tool.summarizer": "ニュース要約",
        "tool.summarizer.desc": "最新情報をリアルタイムで。",
        "tool.copilot": "法的コパイロット",
        "tool.copilot.desc": "戦略的行動計画を策定。",
        "chat.typing": "Cylexが入力中...",
        "analyzer.title": "AI文書分析",
        "analyzer.subtitle": "文書をアップロードして分析。",
        "analyzer.select": "ファイル選択",
        "analyzer.change": "変更",
        "analyzer.btn": "分析",
        "analyzer.loading": "分析中...",
        "analyzer.loading.desc": "リスクを検出中...",
        "analyzer.results": "結果：",
        "summarizer.title": "法的ニュース要約",
        "summarizer.subtitle": "最新ニュースのAI要約。",
        "summarizer.placeholder": "例：最近のデータプライバシー法",
        "summarizer.btn": "要約",
        "summarizer.results": "要約：",
        "summarizer.sources": "ソース：",
        "copilot.title": "AI法的コパイロット",
        "copilot.subtitle": "状況を説明してください。",
        "copilot.label": "事件詳細",
        "copilot.placeholder": "事件を説明してください...",
        "copilot.btn": "計画作成",
        "copilot.results": "行動計画：",
        "copilot.disclaimer": "免責事項：法的助言ではありません。",
        "casedna.title": "事件DNA分析",
        "casedna.subtitle": "事件を視覚的にマッピング。",
        "casedna.placeholder": "事件を説明...",
        "casedna.upload": "文書アップロード",
        "casedna.or": "または",
        "casedna.btn": "分析",
        "casedna.map": "事件DNAマップ",
        "casedna.timeline": "タイムライン",
        "casedna.entities": "主要エンティティ",
        "casedna.evidence": "証拠パターン",
        "casedna.liabilities": "法的責任",
        "riskmeter.title": "サイバーリスクメーター",
        "riskmeter.subtitle": "評価用テキストを貼り付け。",
        "riskmeter.placeholder": "ここにテキストを貼り付け...",
        "riskmeter.btn": "評価",
        "riskmeter.results": "評価結果",
        "riskmeter.level": "リスクレベル：",
        "riskmeter.risk": "特定されたリスク",
        "riskmeter.rec": "推奨事項",
        "predictor.title": "判例予測",
        "predictor.subtitle": "過去のデータで事件を分析。",
        "predictor.placeholder": "事件を説明...",
        "predictor.btn": "予測",
        "predictor.dashboard": "予測ダッシュボード",
        "predictor.outcomes": "予測される結果",
        "predictor.sections": "主要な法的セクション",
        "predictor.strategies": "提案される戦略",
        "about.title": "私たちについて",
        "about.desc": "法と技術の交差点。",
        "about.timeline": "並行する歴史",
        "about.t.1986.title": "コンピュータ詐欺・濫用防止法 (CFAA)",
        "about.t.1986.desc": "コンピュータ犯罪に対処する最初の大規模な米国法。",
        "about.t.1997.title": "ディープ・ブルーがカスパロフに勝利",
        "about.t.1997.desc": "IBMのチェスコンピュータの勝利はAIの大きなマイルストーン。",
        "about.t.2000.title": "E-SIGN法",
        "about.t.2000.desc": "米国における電子署名の合法化。",
        "about.t.2012.title": "AlexNetがImageNetで優勝",
        "about.t.2012.desc": "コンピュータビジョンに革命をもたらした深層学習モデル。",
        "about.t.2016.title": "一般データ保護規則 (GDPR)",
        "about.t.2016.desc": "EUがGDPRを制定し、新たな世界基準を確立。",
        "about.t.2017.title": "Transformerアーキテクチャ",
        "about.t.2017.desc": "Googleの研究者が「Attention Is All You Need」を発表。",
        "about.t.2018.title": "CLOUD法",
        "about.t.2018.desc": "企業にデータ提供を義務付ける米国法。",
        "about.t.2022.title": "ChatGPTの立ち上げ",
        "about.t.2022.desc": "OpenAIによるChatGPTのリリースで生成AIが主流に。",
        "knowledge.title": "知識ハブ",
        "knowledge.subtitle": "サイバー法を探索。",
        "knowledge.back": "戻る",
        "knowledge.overview": "法的概要",
        "knowledge.fetch": "情報取得中...",
        "knowledge.sources": "ソース",
        "knowledge.disclaimer": "免責事項：教育目的のみ。",
        "insights.title": "洞察",
        "insights.subtitle": "専門家の分析。",
        "insights.generate": "要約生成",
        "insights.generating": "処理中...",
        "insights.listen": "聞く",
        "insights.ask": "AIに質問",
        "insights.summary_title": "AI要約：",
        "ticker.threat.1": "金融機関を標的としたアクティブなフィッシングキャンペーンが検出されました。",
        "ticker.threat.2": "広く使用されているサーバーソフトウェアで新しいゼロデイ攻撃が見つかりました。",
        "ticker.threat.3": "ランサムウェア攻撃が主要な医療提供者を混乱させています。",
        "ticker.threat.4": "データ侵害により100万人以上のユーザーの個人情報が流出しました。",
        "ticker.threat.5": "国家支援のスパイウェアマルウェアに対する警告が発令されました。",
        "ticker.insight.1": "最高裁がクラウドコンピューティングにおけるデジタルプライバシーについて判決を下しました。",
        "ticker.insight.2": "国境を越えたデータ事件における知的財産盗難の新たな先例が設定されました。",
        "ticker.insight.3": "コンプライアンス違反に対して画期的なGDPR罰金が科されました。",
        "ticker.insight.4": "分析：AI生成コンテンツの著作権に関する最近の判決。",
        "ticker.insight.5": "リーガルテックトレンド：訴訟における予測分析。",
    },
    pt: {
        "hero.title": "O Futuro da Lei Encontra a Inteligência Cibernética",
        "hero.subtitle.1": "Seu Caso, Nosso Código.",
        "hero.subtitle.2": "Onde a Justiça Encontra Algoritmos.",
        "nav.home": "Início",
        "nav.templates": "Modelos",
        "nav.knowledge": "Conhecimento",
        "nav.insights": "Insights",
        "nav.labs": "Laboratórios",
        "nav.tools": "Ferramentas",
        "nav.engage": "Engajamento",
        "nav.about": "Sobre",
        "section.toolkit": "Inteligência Jurídica de Próxima Geração",
        "section.toolkit.title": "Nosso Kit Jurídico com IA",
        "section.toolkit.desc": "Implantando redes neurais avançadas para decodificar complexidades legais.",
        "region.eu": "União Europeia",
        "region.us": "Estados Unidos",
        "region.br": "Brasil",
        "region.in": "Índia",
        "region.jp": "Japão",
        "region.au": "Austrália",
        "engage.title": "Hub de Engajamento",
        "engage.subtitle": "Interaja com nossas ferramentas de IA.",
        "engage.voice.title": "Consulta por Voz",
        "engage.voice.desc": "Fale diretamente com Cylex para uma consulta sem as mãos.",
        "engage.quiz.title": "Expert em Ciberdireito?",
        "engage.quiz.desc": "Teste seus conhecimentos com nosso quiz gerado por IA.",
        "engage.news.title": "Boletim Jurídico IA",
        "engage.news.desc": "Gere um boletim personalizado com as últimas atualizações.",
        "engage.back": "Voltar",
        "voice.title": "Consulta de Voz IA",
        "voice.subtitle": "Fale diretamente com Cylex.",
        "voice.back": "Voltar",
        "voice.status.connected": "Conectado",
        "voice.status.connecting": "Conectando...",
        "voice.status.error": "Erro",
        "voice.status.disconnected": "Desconectado",
        "voice.btn.start": "Iniciar Consulta",
        "voice.btn.end": "Encerrar Consulta",
        "voice.listening": "Cylex está ouvindo...",
        "voice.live.disclaimer": "Esta é uma consulta ao vivo. Seu microfone está ativo.",
        "quiz.title": "Expert em Ciberdireito?",
        "quiz.subtitle": "Um quiz gamificado para testar sua expertise.",
        "quiz.back": "Voltar",
        "quiz.loading": "Gerando seu quiz...",
        "quiz.complete": "Quiz Completo!",
        "quiz.score": "Sua pontuação",
        "quiz.play_again": "Jogar Novamente",
        "quiz.question_count": "Pergunta",
        "quiz.of": "de",
        "quiz.explanation": "Explicação:",
        "quiz.next": "Próxima Pergunta",
        "quiz.finish": "Terminar",
        "quiz.start_prompt": "Pronto para testar seu conhecimento?",
        "quiz.start_desc": "Obtenha um quiz único gerado por IA.",
        "quiz.start_btn": "Iniciar Quiz",
        "news.title": "Gerador de Boletim",
        "news.subtitle": "Obtenha um boletim jurídico personalizado.",
        "news.back": "Voltar",
        "news.placeholder": "ex., União Europeia",
        "news.btn": "Gerar",
        "news.loading": "Gerando boletim...",
        "news.result_title": "Seu Boletim Personalizado",
        "news.sources": "Fontes Usadas:",
        "templates.title": "Biblioteca de Modelos",
        "templates.subtitle": "Coleção de documentos prontos.",
        "templates.copy": "Copiar",
        "templates.copied": "Copiado!",
        "templates.customize": "Personalizar",
        "templates.category.all": "Todos",
        "templates.cat.ip": "Propriedade Intelectual",
        "templates.cat.privacy": "Privacidade",
        "templates.cat.contracts": "Contratos",
        "templates.t1.title": "Carta de Cessar e Desistir",
        "templates.t1.desc": "Demanda formal para parar atividade ilegal.",
        "templates.t1.content": "[Seu Nome]\n[Endereço]\n[Data]\n\nPrezado [Nome],\n\nEsta carta serve como uma demanda formal para que CESSE E DESISTA imediatamente todo uso não autorizado da propriedade intelectual de [Sua Empresa]. Exigimos a remoção imediata.\n\nAtenciosamente,\n[Seu Nome]",
        "templates.t2.title": "Política de Privacidade",
        "templates.t2.desc": "Modelo básico de política de privacidade.",
        "templates.t2.content": "POLÍTICA DE PRIVACIDADE\n\n[Sua Empresa] coleta dados para melhorar nosso serviço. Podemos coletar Dados Pessoais e Dados de Uso.",
        "templates.t3.title": "Acordo de Não Divulgação (NDA)",
        "templates.t3.desc": "NDA padrão para proteger informações confidenciais.",
        "templates.t3.content": "ACORDO DE NÃO DIVULGAÇÃO\n\nEste Acordo é entre [Parte 1] e [Parte 2]. Ambas as partes concordam em não divulgar informações confidenciais a terceiros.",
        "templates.t4.title": "Notificação de Violação de Dados",
        "templates.t4.desc": "Modelo para notificar sobre violação de dados.",
        "templates.t4.content": "AVISO DE INCIDENTE DE DADOS\n\nPrezado [Nome],\n\nEscrevemos para informar sobre um incidente de segurança. Em [Data], descobrimos acesso não autorizado.",
        "insights.a1.title": "Impacto do GDPR na IA",
        "insights.a1.snippet": "Examinando a interação entre GDPR e IA.",
        "insights.a1.content": "O GDPR continua moldando o cenário digital. Para desenvolvedores de IA, apresenta desafios únicos sobre minimização de dados.",
        "insights.a2.title": "Forense Digital na Nuvem",
        "insights.a2.snippet": "Complexidades legais de investigações na nuvem.",
        "insights.a2.content": "A computação em nuvem revolucionou o armazenamento, mas complicou investigações. Qual lei se aplica?",
        "insights.a3.title": "Direitos Autorais e Arte IA",
        "insights.a3.snippet": "O debate sobre direitos autorais e IA generativa.",
        "insights.a3.content": "Decisões recentes negaram proteção de direitos autorais a trabalhos gerados puramente por IA.",
        "labs.title": "Laboratórios IA",
        "labs.subtitle": "Um vislumbre do futuro.",
        "labs.coming_soon": "Em Breve",
        "labs.status.experimental": "Experimental",
        "labs.status.development": "Em Desenvolvimento",
        "labs.status.concept": "Conceito",
        "tool.predictor": "Preditores de Precedentes",
        "tool.predictor.desc": "Preveja resultados.",
        "tool.riskmeter": "Medidor de Risco",
        "tool.riskmeter.desc": "Quantifique exposição legal.",
        "tool.casedna": "Análise de DNA do Caso",
        "tool.casedna.desc": "Desconstrua casos complexos.",
        "tool.templates": "Modelos Jurídicos",
        "tool.templates.desc": "Gere documentos.",
        "tool.knowledge": "Hub de Conhecimento",
        "tool.knowledge.desc": "Navegue por leis globais.",
        "tool.analyzer": "Análise de Documentos",
        "tool.analyzer.desc": "Detecção de riscos.",
        "tool.summarizer": "Resumo de Notícias",
        "tool.summarizer.desc": "Mantenha-se atualizado.",
        "tool.copilot": "Copiloto Jurídico",
        "tool.copilot.desc": "Planos de ação estratégicos.",
        "chat.typing": "Cylex está digitando...",
        "analyzer.title": "Análise de Documentos IA",
        "analyzer.subtitle": "Faça upload de um documento.",
        "analyzer.select": "Selecionar arquivo",
        "analyzer.change": "Alterar",
        "analyzer.btn": "Analisar",
        "analyzer.loading": "Analisando...",
        "analyzer.loading.desc": "Detectando riscos...",
        "analyzer.results": "Resultados:",
        "summarizer.title": "Resumo de Notícias",
        "summarizer.subtitle": "Resumos de IA das últimas notícias.",
        "summarizer.placeholder": "ex., leis de privacidade",
        "summarizer.btn": "Resumir",
        "summarizer.results": "Resumo:",
        "summarizer.sources": "Fontes:",
        "copilot.title": "Copiloto Jurídico IA",
        "copilot.subtitle": "Descreva sua situação.",
        "copilot.label": "Detalhes do Caso",
        "copilot.placeholder": "Descreva o incidente...",
        "copilot.btn": "Gerar Plano",
        "copilot.results": "Plano de Ação:",
        "copilot.disclaimer": "Aviso: Não é aconselhamento jurídico.",
        "casedna.title": "Análise de DNA do Caso",
        "casedna.subtitle": "Mapeie visualmente seu caso.",
        "casedna.placeholder": "Descreva o incidente...",
        "casedna.upload": "Upload de Documento",
        "casedna.or": "OU",
        "casedna.btn": "Analisar",
        "casedna.map": "Mapa de DNA do Caso",
        "casedna.timeline": "Linha do Tempo",
        "casedna.entities": "Entidades Chave",
        "casedna.evidence": "Padrões de Evidência",
        "casedna.liabilities": "Responsabilidades",
        "riskmeter.title": "Medidor de Risco",
        "riskmeter.subtitle": "Cole o texto para avaliação.",
        "riskmeter.placeholder": "Cole o texto aqui...",
        "riskmeter.btn": "Avaliar",
        "riskmeter.results": "Resultados",
        "riskmeter.level": "Nível de Risco:",
        "riskmeter.risk": "Risco Identificado",
        "riskmeter.rec": "Recomendação",
        "predictor.title": "Preditores de Precedentes",
        "predictor.subtitle": "Analise com dados históricos.",
        "predictor.placeholder": "Descreva o caso...",
        "predictor.btn": "Prever",
        "predictor.dashboard": "Painel de Previsão",
        "predictor.outcomes": "Resultados Previstos",
        "predictor.sections": "Seções Legais",
        "predictor.strategies": "Estratégias",
        "about.title": "Sobre Nós",
        "about.desc": "Interseção de lei e tecnologia.",
        "about.timeline": "História Paralela",
        "about.t.1986.title": "Computer Fraud and Abuse Act (CFAA)",
        "about.t.1986.desc": "Primeira grande legislação dos EUA sobre crimes cibernéticos.",
        "about.t.1997.title": "Deep Blue derrota Garry Kasparov",
        "about.t.1997.desc": "A vitória do computador de xadrez da IBM marcou um marco na IA.",
        "about.t.2000.title": "Lei E-SIGN",
        "about.t.2000.desc": "Legalizou assinaturas eletrônicas nos EUA.",
        "about.t.2012.title": "AlexNet vence ImageNet",
        "about.t.2012.desc": "Modelo de aprendizagem profunda que revolucionou a visão computacional.",
        "about.t.2016.title": "Regulamento Geral sobre a Proteção de Dados (GDPR)",
        "about.t.2016.desc": "A UE promulgou o GDPR, estabelecendo um novo padrão global.",
        "about.t.2017.title": "Arquitetura Transformers",
        "about.t.2017.desc": "Pesquisadores do Google publicam 'Attention Is All You Need'.",
        "about.t.2018.title": "Lei CLOUD",
        "about.t.2018.desc": "Lei dos EUA permitindo obrigar empresas a fornecer dados.",
        "about.t.2022.title": "Lançamento do ChatGPT",
        "about.t.2022.desc": "O lançamento do ChatGPT pela OpenAI popularizou a IA generativa.",
        "knowledge.title": "Hub de Conhecimento",
        "knowledge.subtitle": "Explore leis globais.",
        "knowledge.back": "Voltar",
        "knowledge.overview": "Visão Geral",
        "knowledge.fetch": "Buscando informações...",
        "knowledge.sources": "Fontes",
        "knowledge.disclaimer": "Aviso: Apenas educacional.",
        "insights.title": "Insights",
        "insights.subtitle": "Sua fonte especializada.",
        "insights.generate": "Gerar Resumo",
        "insights.generating": "Gerando...",
        "insights.listen": "Ouvir",
        "insights.ask": "Perguntar à IA",
        "insights.summary_title": "Resumo IA:",
        "ticker.threat.1": "Campanha de phishing ativa visando instituições financeiras detectada.",
        "ticker.threat.2": "Novo exploit Zero-Day encontrado em software de servidor amplamente utilizado.",
        "ticker.threat.3": "Ataque de ransomware interrompe grande provedor de saúde.",
        "ticker.threat.4": "Violação de dados expõe informações pessoais de mais de 1 milhão de usuários.",
        "ticker.threat.5": "Aviso emitido para malware de espionagem patrocinado pelo estado.",
        "ticker.insight.1": "Suprema Corte decide sobre privacidade digital na computação em nuvem.",
        "ticker.insight.2": "Novo precedente estabelecido para roubo de PI em um caso de dados transfronteiriços.",
        "ticker.insight.3": "Multa histórica do GDPR emitida por não conformidade.",
        "ticker.insight.4": "Análise: Decisão recente sobre direitos autorais de conteúdo gerado por IA.",
        "ticker.insight.5": "Tendências de Legal Tech: Análise preditiva em litígios.",
    },
    nl: {
        "hero.title": "De Toekomst van het Recht Ontmoet Cyber Intelligentie",
        "hero.subtitle.1": "Uw zaak, onze code.",
        "hero.subtitle.2": "Waar gerechtigheid algoritmen ontmoet.",
        "nav.home": "Home",
        "nav.templates": "Sjablonen",
        "nav.knowledge": "Kennis Hub",
        "nav.insights": "Inzichten",
        "nav.labs": "AI Labs",
        "nav.tools": "Tools",
        "nav.engage": "Doe mee",
        "nav.about": "Over ons",
        "section.toolkit": "Next-Gen Juridische Intelligentie",
        "section.toolkit.title": "Onze AI-Aangedreven Juridische Toolkit",
        "section.toolkit.desc": "Geavanceerde neurale netwerken inzetten om juridische complexiteit te decoderen.",
        "region.eu": "Europese Unie",
        "region.us": "Verenigde Staten",
        "region.br": "Brazilië",
        "region.in": "India",
        "region.jp": "Japan",
        "region.au": "Australië",
        "engage.title": "Engagement Hub",
        "engage.subtitle": "Interactie met onze geavanceerde AI-tools.",
        "engage.voice.title": "Spraakconsultatie",
        "engage.voice.desc": "Spreek direct met Cylex voor een handsfree consult.",
        "engage.quiz.title": "Ben jij Cyberwet Expert?",
        "engage.quiz.desc": "Test je kennis met onze AI-gegenereerde quiz.",
        "engage.news.title": "AI Juridische Nieuwsbrief",
        "engage.news.desc": "Genereer een gepersonaliseerde nieuwsbrief met de laatste updates.",
        "engage.back": "Terug",
        "voice.title": "AI Spraakconsultatie",
        "voice.subtitle": "Spreek direct met Cylex.",
        "voice.back": "Terug",
        "voice.status.connected": "Verbonden",
        "voice.status.connecting": "Verbinden...",
        "voice.status.error": "Fout",
        "voice.status.disconnected": "Verbinding verbroken",
        "voice.btn.start": "Start Consult",
        "voice.btn.end": "Beëindig Consult",
        "voice.listening": "Cylex luistert...",
        "voice.live.disclaimer": "Dit is een live consult. Je microfoon is actief.",
        "quiz.title": "Ben jij Cyberwet Expert?",
        "quiz.subtitle": "Een speelse quiz om je expertise te testen.",
        "quiz.back": "Terug",
        "quiz.loading": "Quiz genereren...",
        "quiz.complete": "Quiz Voltooid!",
        "quiz.score": "Je score",
        "quiz.play_again": "Opnieuw Spelen",
        "quiz.question_count": "Vraag",
        "quiz.of": "van",
        "quiz.explanation": "Uitleg:",
        "quiz.next": "Volgende Vraag",
        "quiz.finish": "Voltooien",
        "quiz.start_prompt": "Klaar om je kennis te testen?",
        "quiz.start_desc": "Krijg een unieke, AI-gegenereerde quiz.",
        "quiz.start_btn": "Start Quiz",
        "news.title": "Nieuwsbrief Generator",
        "news.subtitle": "Ontvang een gepersonaliseerde juridische nieuwsbrief.",
        "news.back": "Terug",
        "news.placeholder": "bijv. Europese Unie",
        "news.btn": "Genereren",
        "news.loading": "Nieuwsbrief genereren...",
        "news.result_title": "Je Aangepaste Nieuwsbrief",
        "news.sources": "Gebruikte bronnen:",
        "templates.title": "Sjablonen Bibliotheek",
        "templates.subtitle": "Toegang tot kant-en-klare juridische documenten.",
        "templates.copy": "Kopiëren",
        "templates.copied": "Gekopieerd!",
        "templates.customize": "Aanpassen",
        "templates.category.all": "Alle",
        "templates.cat.ip": "Intellectueel Eigendom",
        "templates.cat.privacy": "Gegevensprivacy",
        "templates.cat.contracts": "Contracten",
        "templates.t1.title": "Sommatiebrief",
        "templates.t1.desc": "Formeel verzoek om illegale activiteiten te stoppen.",
        "templates.t1.content": "[Uw Naam]\n[Adres]\n[Datum]\n\nGeachte [Naam],\n\nDeze brief dient als een formeel verzoek om ONMIDDELLIJK te stoppen met elk ongeoorloofd gebruik van het intellectuele eigendom van [Uw Bedrijf]. Wij eisen onmiddellijke verwijdering.\n\nHoogachtend,\n[Uw Naam]",
        "templates.t2.title": "Privacybeleid",
        "templates.t2.desc": "Basis sjabloon voor privacybeleid.",
        "templates.t2.content": "PRIVACYBELEID\n\n[Uw Bedrijf] verzamelt gegevens om onze service te verbeteren. We kunnen persoonlijke gegevens en gebruiksgegevens verzamelen.",
        "templates.t3.title": "Geheimhoudingsovereenkomst (NDA)",
        "templates.t3.desc": "Standaard NDA om vertrouwelijke informatie te beschermen.",
        "templates.t3.content": "GEHEIMHOUDINGSOVEREENKOMST\n\nDeze overeenkomst is tussen [Partij 1] en [Partij 2]. Beide partijen komen overeen vertrouwelijke informatie niet te onthullen.",
        "templates.t4.title": "Melding Datalek",
        "templates.t4.desc": "Sjabloon voor het melden van een datalek.",
        "templates.t4.content": "KENNISGEVING VAN DATA-INCIDENT\n\nGeachte [Naam],\n\nWij schrijven u om u te informeren over een beveiligingsincident. Op [Datum] ontdekten wij ongeautoriseerde toegang.",
        "insights.a1.title": "Impact van AVG op AI",
        "insights.a1.snippet": "Onderzoek naar de interactie tussen AVG en AI.",
        "insights.a1.content": "De AVG blijft het digitale landschap vormen. Voor AI-ontwikkelaars biedt het unieke uitdagingen rond dataminimalisatie.",
        "insights.a2.title": "Digitaal Forensisch in de Cloud",
        "insights.a2.snippet": "Juridische complexiteit van cloud-onderzoeken.",
        "insights.a2.content": "Cloud computing heeft opslag veranderd maar onderzoeken bemoeilijkt. Welke wet is van toepassing?",
        "insights.a3.title": "Auteursrecht en AI-Kunst",
        "insights.a3.snippet": "Het debat over auteursrecht en generatieve AI.",
        "insights.a3.content": "Recente beslissingen weigeren auteursrechtbescherming voor puur AI-gegenereerde werken.",
        "labs.title": "AI Labs",
        "labs.subtitle": "Een blik op de toekomst.",
        "labs.coming_soon": "Binnenkort",
        "labs.status.experimental": "Experimenteel",
        "labs.status.development": "In Ontwikkeling",
        "labs.status.concept": "Concept",
        "tool.predictor": "Precedent Voorspeller",
        "tool.predictor.desc": "Voorspel uitkomsten.",
        "tool.riskmeter": "Cyber Risicometer",
        "tool.riskmeter.desc": "Kwantificeer juridische blootstelling.",
        "tool.casedna": "Zaak DNA Analyse",
        "tool.casedna.desc": "Deconstrueer complexe zaken.",
        "tool.templates": "Juridische Sjablonen",
        "tool.templates.desc": "Genereer documenten.",
        "tool.knowledge": "Kennis Hub",
        "tool.knowledge.desc": "Navigeer wereldwijde wetten.",
        "tool.analyzer": "Document Analyse",
        "tool.analyzer.desc": "Automatische risicodetectie.",
        "tool.summarizer": "Nieuws Samenvatter",
        "tool.summarizer.desc": "Blijf op de hoogte.",
        "tool.copilot": "Juridische Copiloot",
        "tool.copilot.desc": "Strategische actieplannen.",
        "chat.typing": "Cylex is aan het typen...",
        "analyzer.title": "AI Document Analyse",
        "analyzer.subtitle": "Upload een document voor analyse.",
        "analyzer.select": "Selecteer bestand",
        "analyzer.change": "Wijzigen",
        "analyzer.btn": "Analyseren",
        "analyzer.loading": "Analyseren...",
        "analyzer.loading.desc": "Risico's detecteren...",
        "analyzer.results": "Resultaten:",
        "summarizer.title": "Juridisch Nieuws Samenvatter",
        "summarizer.subtitle": "AI-samenvattingen van het laatste nieuws.",
        "summarizer.placeholder": "bijv., recente privacywetten",
        "summarizer.btn": "Samenvatten",
        "summarizer.results": "Samenvatting:",
        "summarizer.sources": "Bronnen:",
        "copilot.title": "AI Juridische Copiloot",
        "copilot.subtitle": "Beschrijf uw situatie.",
        "copilot.label": "Zaakdetails",
        "copilot.placeholder": "Beschrijf het incident...",
        "copilot.btn": "Genereer Plan",
        "copilot.results": "Actieplan:",
        "copilot.disclaimer": "Disclaimer: Geen juridisch advies.",
        "casedna.title": "Zaak DNA Analyse",
        "casedna.subtitle": "Breng uw zaak visueel in kaart.",
        "casedna.placeholder": "Beschrijf het incident...",
        "casedna.upload": "Document Uploaden",
        "casedna.or": "OF",
        "casedna.btn": "Analyseren",
        "casedna.map": "Zaak DNA Kaart",
        "casedna.timeline": "Tijdlijn",
        "casedna.entities": "Belangrijke Entiteiten",
        "casedna.evidence": "Bewijspatronen",
        "casedna.liabilities": "Aansprakelijkheden",
        "riskmeter.title": "Cyber Risicometer",
        "riskmeter.subtitle": "Plak uw beleid voor evaluatie.",
        "riskmeter.placeholder": "Plak tekst hier...",
        "riskmeter.btn": "Beoordelen",
        "riskmeter.results": "Resultaten",
        "riskmeter.level": "Risiconiveau:",
        "riskmeter.risk": "Geïdentificeerd Risico",
        "riskmeter.rec": "Aanbeveling",
        "predictor.title": "Precedent Voorspeller",
        "predictor.subtitle": "Analyseer met historische gegevens.",
        "predictor.placeholder": "Beschrijf uw zaak...",
        "predictor.btn": "Voorspellen",
        "predictor.dashboard": "Voorspellingsdashboard",
        "predictor.outcomes": "Verwachte Uitkomsten",
        "predictor.sections": "Wetsartikelen",
        "predictor.strategies": "Strategieën",
        "about.title": "Over Ons",
        "about.desc": "Kruispunt van recht en technologie.",
        "about.timeline": "Een Parallelle Geschiedenis",
        "about.t.1986.title": "Computer Fraud and Abuse Act (CFAA)",
        "about.t.1986.desc": "De eerste grote Amerikaanse wetgeving tegen computercriminaliteit.",
        "about.t.1997.title": "Deep Blue verslaat Garry Kasparov",
        "about.t.1997.desc": "De overwinning van IBM's schaakcomputer was een mijlpaal voor AI.",
        "about.t.2000.title": "E-SIGN Act",
        "about.t.2000.desc": "Legaliseerde elektronische handtekeningen in de VS.",
        "about.t.2012.title": "AlexNet wint ImageNet",
        "about.t.2012.desc": "Deep learning model dat computervisie revolutioneerde.",
        "about.t.2016.title": "Algemene Verordening Gegevensbescherming (AVG)",
        "about.t.2016.desc": "De EU voerde de AVG in, een nieuwe wereldwijde standaard.",
        "about.t.2017.title": "Transformer Architectuur",
        "about.t.2017.desc": "Google-onderzoekers publiceren 'Attention Is All You Need'.",
        "about.t.2018.title": "CLOUD Act",
        "about.t.2018.desc": "Amerikaanse wet die bedrijven verplicht gegevens te verstrekken.",
        "about.t.2022.title": "Lancering van ChatGPT",
        "about.t.2022.desc": "De lancering van ChatGPT door OpenAI bracht generatieve AI naar het grote publiek.",
        "knowledge.title": "Kennis Hub",
        "knowledge.subtitle": "Verken wereldwijde wetten.",
        "knowledge.back": "Terug",
        "knowledge.overview": "Juridisch Overzicht",
        "knowledge.fetch": "Informatie ophalen...",
        "knowledge.sources": "Bronnen",
        "knowledge.disclaimer": "Disclaimer: Alleen voor educatie.",
        "insights.title": "Inzichten",
        "insights.subtitle": "Uw expertbron.",
        "insights.generate": "Samenvatten",
        "insights.generating": "Bezig...",
        "insights.listen": "Luisteren",
        "insights.ask": "Vraag AI",
        "insights.summary_title": "AI Samenvatting:",
        "ticker.threat.1": "Actieve phishingcampagne gericht op financiële instellingen gedetecteerd.",
        "ticker.threat.2": "Nieuwe Zero-Day Exploit gevonden in veelgebruikte serversoftware.",
        "ticker.threat.3": "Ransomware-aanval verstoort grote zorgverlener.",
        "ticker.threat.4": "Datalek stelt persoonlijke gegevens van 1M+ gebruikers bloot.",
        "ticker.threat.5": "Waarschuwing afgegeven voor door de staat gesponsorde spionagemalware.",
        "ticker.insight.1": "Hooggerechtshof doet uitspraak over digitale privacy in cloud computing.",
        "ticker.insight.2": "Nieuw precedent voor IP-diefstal in een grensoverschrijdende gegevenszaak.",
        "ticker.insight.3": "Baanbrekende AVG-boete opgelegd wegens niet-naleving.",
        "ticker.insight.4": "Analyse: Recente uitspraak over auteursrecht op AI-gegenereerde inhoud.",
        "ticker.insight.5": "Legal Tech Trends: Voorspellende analyse in rechtszaken.",
    }
};

export const translate = (key: string, lang: LanguageCode): string => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en'][key] || key;
};
